[build-system]
requires = ["setuptools>=61", "wheel", "pybind11>=2.11"]
build-backend = "setuptools.build_meta"

[project]
name = "pycircuit"
version = "0.0"
description = "Python circuit design tools"
authors = [
    {name = "Henrik Johansson", email = "henjo2006@gmail.com"},
    {name = "Joacim Olsson"},
    {name = "Andreas Drejfert"},
]
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "scipy",
    "sympy",
    "jax",
    "pydot",
    "polars-waveform>=0.1",
    "pytest-xdist>=3.8.0",
]

[project.optional-dependencies]
psf = ["polars-psf>=0.1"]
dev = ["pytest", "matplotlib", "pexpect", "polars-psf>=0.1"]
ginac = ["pybind11>=2.11"]
docs = ["sphinx", "matplotlib", "pexpect"]

[tool.setuptools.packages.find]
where = ["."]
include = ["pycircuit*"]
