/*
 * Internal module API header file.
 *
 * Generated by SIP 4.7.5 on Fri May 16 20:39:45 2008
 */

#ifndef _jwdbAPI_H
#define _jwdbAPI_H


#include <sip.h>

/* Convenient names to call the SIP API. */
#define sipConvertFromSliceObject(o,len,start,stop,step,slen)   PySlice_GetIndicesEx((PySliceObject *)(o),(len),(start),(stop),(step),(slen))
#define sipIsSubClassInstance(o,wt) PyObject_TypeCheck((o),(PyTypeObject *)(wt))

#define sipMapStringToClass         sipAPI_jwdb->api_map_string_to_class
#define sipMapIntToClass            sipAPI_jwdb->api_map_int_to_class
#define sipMalloc                   sipAPI_jwdb->api_malloc
#define sipFree                     sipAPI_jwdb->api_free
#define sipBuildResult              sipAPI_jwdb->api_build_result
#define sipCallMethod               sipAPI_jwdb->api_call_method
#define sipParseResult              sipAPI_jwdb->api_parse_result
#define sipParseArgs                sipAPI_jwdb->api_parse_args
#define sipParsePair                sipAPI_jwdb->api_parse_pair
#define sipCommonCtor               sipAPI_jwdb->api_common_ctor
#define sipCommonDtor               sipAPI_jwdb->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_jwdb->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_jwdb->api_convert_from_void_ptr
#define sipConvertToCpp             sipAPI_jwdb->api_convert_to_cpp
#define sipConvertToVoidPtr         sipAPI_jwdb->api_convert_to_void_ptr
#define sipNoFunction               sipAPI_jwdb->api_no_function
#define sipNoMethod                 sipAPI_jwdb->api_no_method
#define sipAbstractMethod           sipAPI_jwdb->api_abstract_method
#define sipBadClass                 sipAPI_jwdb->api_bad_class
#define sipBadSetType               sipAPI_jwdb->api_bad_set_type
#define sipBadCatcherResult         sipAPI_jwdb->api_bad_catcher_result
#define sipBadOperatorArg           sipAPI_jwdb->api_bad_operator_arg
#define sipTrace                    sipAPI_jwdb->api_trace
#define sipTransfer                 sipAPI_jwdb->api_transfer
#define sipTransferBack             sipAPI_jwdb->api_transfer_back
#define sipTransferTo               sipAPI_jwdb->api_transfer_to
#define sipTransferBreak            sipAPI_jwdb->api_transfer_break
#define sipWrapper_Check            sipAPI_jwdb->api_wrapper_check
#define sipGetWrapper               sipAPI_jwdb->api_get_wrapper
#define sipGetCppPtr                sipAPI_jwdb->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_jwdb->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_jwdb->api_is_py_method
#define sipCallHook                 sipAPI_jwdb->api_call_hook
#define sipStartThread              sipAPI_jwdb->api_start_thread
#define sipEndThread                sipAPI_jwdb->api_end_thread
#define sipEmitSignal               sipAPI_jwdb->api_emit_signal
#define sipConnectRx                sipAPI_jwdb->api_connect_rx
#define sipDisconnectRx             sipAPI_jwdb->api_disconnect_rx
#define sipGetSender                sipAPI_jwdb->api_get_sender
#define sipRaiseUnknownException    sipAPI_jwdb->api_raise_unknown_exception
#define sipRaiseClassException      sipAPI_jwdb->api_raise_class_exception
#define sipRaiseSubClassException   sipAPI_jwdb->api_raise_sub_class_exception
#define sipBadLengthForSlice        sipAPI_jwdb->api_bad_length_for_slice
#define sipClassName                sipAPI_jwdb->api_class_name
#define sipAddClassInstance         sipAPI_jwdb->api_add_class_instance
#define sipAddMappedTypeInstance    sipAPI_jwdb->api_add_mapped_type_instance
#define sipAddEnumInstance          sipAPI_jwdb->api_add_enum_instance
#define sipConvertFromNamedEnum     sipAPI_jwdb->api_convert_from_named_enum
#define sipGetAddress               sipAPI_jwdb->api_get_address
#define sipFreeConnection           sipAPI_jwdb->api_free_connection
#define sipEmitToSlot               sipAPI_jwdb->api_emit_to_slot
#define sipSameConnection           sipAPI_jwdb->api_same_connection
#define sipPySlotExtend             sipAPI_jwdb->api_pyslot_extend
#define sipConvertRx                sipAPI_jwdb->api_convert_rx
#define sipAddDelayedDtor           sipAPI_jwdb->api_add_delayed_dtor
#define sipCanConvertToInstance     sipAPI_jwdb->api_can_convert_to_instance
#define sipCanConvertToMappedType   sipAPI_jwdb->api_can_convert_to_mapped_type
#define sipConvertToInstance        sipAPI_jwdb->api_convert_to_instance
#define sipConvertToMappedType      sipAPI_jwdb->api_convert_to_mapped_type
#define sipForceConvertToInstance   sipAPI_jwdb->api_force_convert_to_instance
#define sipForceConvertToMappedType sipAPI_jwdb->api_force_convert_to_mapped_type
#define sipReleaseInstance          sipAPI_jwdb->api_release_instance
#define sipReleaseMappedType        sipAPI_jwdb->api_release_mapped_type
#define sipConvertFromInstance      sipAPI_jwdb->api_convert_from_instance
#define sipConvertFromNewInstance   sipAPI_jwdb->api_convert_from_new_instance
#define sipConvertFromMappedType    sipAPI_jwdb->api_convert_from_mapped_type
#define sipGetState                 sipAPI_jwdb->api_get_state
#define sipFindMappedType           sipAPI_jwdb->api_find_mapped_type
#define sipLong_AsUnsignedLong      sipAPI_jwdb->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_jwdb->api_export_symbol
#define sipImportSymbol             sipAPI_jwdb->api_import_symbol
#define sipRegisterIntTypes         sipAPI_jwdb->api_register_int_types
#define sipParseSignature           sipAPI_jwdb->api_parse_signature
#define sipFindClass                sipAPI_jwdb->api_find_class
#define sipFindNamedEnum            sipAPI_jwdb->api_find_named_enum
#define sipString_AsChar            sipAPI_jwdb->api_string_as_char
#define sipUnicode_AsWChar          sipAPI_jwdb->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_jwdb->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_jwdb->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_jwdb->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_jwdb->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_jwdb->api_invoke_slot
#define sipParseType                sipAPI_jwdb->api_parse_type
#define sipIsExactWrappedType       sipAPI_jwdb->api_is_exact_wrapped_type
#define sipAssignInstance           sipAPI_jwdb->api_assign_instance
#define sipAssignMappedType         sipAPI_jwdb->api_assign_mapped_type

/* The strings used by this module. */
extern char sipNm_jwdb_ams_sim_read_digital_x_y_data_v1[];
extern char sipNm_jwdb_ams_sim_read_analog_x_y_data_v1[];
extern char sipNm_jwdb_ams_sim_close_read_file[];
extern char sipNm_jwdb_ams_sim_get_digital_x_y_data[];
extern char sipNm_jwdb_ams_sim_get_analog_x_y_data[];
extern char sipNm_jwdb_ams_sim_get_x_data[];
extern char sipNm_jwdb_ams_sim_read_mixed_x_y_data[];
extern char sipNm_jwdb_ams_sim_read_digital_x_y_data[];
extern char sipNm_jwdb_ams_sim_read_analog_x_y_data_complex[];
extern char sipNm_jwdb_ams_sim_read_analog_x_y_data[];
extern char sipNm_jwdb_ams_read_selected_digital_waves[];
extern char sipNm_jwdb_ams_read_selected_waves_complex[];
extern char sipNm_jwdb_ams_read_selected_waves[];
extern char sipNm_jwdb_ams_sim_set_simulation_read_stop[];
extern char sipNm_jwdb_ams_sim_set_simulation_read_start[];
extern char sipNm_jwdb_ams_sim_is_wave_digital[];
extern char sipNm_jwdb_ams_sim_is_wave_analog[];
extern char sipNm_jwdb_ams_sim_is_wave_complex[];
extern char sipNm_jwdb_ams_sim_get_wave_unit_name[];
extern char sipNm_jwdb_ams_sim_is_analog_wave[];
extern char sipNm_jwdb_ams_sim_get_index_to_extract_waveform[];
extern char sipNm_jwdb_ams_sim_get_next_waveform_name[];
extern char sipNm_jwdb_ams_sim_get_next_waveform_index[];
extern char sipNm_jwdb_ams_sim_get_simulation_parameter_info[];
extern char sipNm_jwdb_ams_sim_get_simulation_parameter_number[];
extern char sipNm_jwdb_ams_sim_get_creation_time[];
extern char sipNm_jwdb_ams_sim_get_creation_date[];
extern char sipNm_jwdb_ams_sim_get_x_unit_name[];
extern char sipNm_jwdb_ams_sim_set_simulation_xstop[];
extern char sipNm_jwdb_ams_sim_set_simulation_xstart[];
extern char sipNm_jwdb_ams_sim_load_simu_with_complex_by_index[];
extern char sipNm_jwdb_ams_sim_load_simu_with_complex[];
extern char sipNm_jwdb_ams_sim_load_simu_by_index[];
extern char sipNm_jwdb_ams_sim_load_simu[];
extern char sipNm_jwdb_ams_sim_is_compat_file[];
extern char sipNm_jwdb_ams_sim_is_cou_file[];
extern char sipNm_jwdb_ams_sim_is_wdb_file[];
extern char sipNm_jwdb_ams_sim_is_jwdb_file[];
extern char sipNm_jwdb_ams_sim_open_read_file[];
extern char sipNm_jwdb_ams_sim_set_jwdb_server[];
extern char sipNm_jwdb_ams_sim_set_multirun_mode[];
extern char sipNm_jwdb_ams_sim_set_data_blocksize[];
extern char sipNm_jwdb_ams_sim_set_connection_message[];
extern char sipNm_jwdb_ams_sim_init_file[];

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_jwdb;
extern sipExportedModuleDef sipModuleAPI_jwdb;

#endif
