/*
 * Module code.
 *
 * Generated by SIP 4.7.5 on Fri May 16 20:39:45 2008
 */

#include "sipAPIjwdb.h"


/* Define the strings used by this module. */
char sipNm_jwdb_ams_sim_read_digital_x_y_data_v1[] = "ams_sim_read_digital_x_y_data_v1";
char sipNm_jwdb_ams_sim_read_analog_x_y_data_v1[] = "ams_sim_read_analog_x_y_data_v1";
char sipNm_jwdb_ams_sim_close_read_file[] = "ams_sim_close_read_file";
char sipNm_jwdb_ams_sim_get_digital_x_y_data[] = "ams_sim_get_digital_x_y_data";
char sipNm_jwdb_ams_sim_get_analog_x_y_data[] = "ams_sim_get_analog_x_y_data";
char sipNm_jwdb_ams_sim_get_x_data[] = "ams_sim_get_x_data";
char sipNm_jwdb_ams_sim_read_mixed_x_y_data[] = "ams_sim_read_mixed_x_y_data";
char sipNm_jwdb_ams_sim_read_digital_x_y_data[] = "ams_sim_read_digital_x_y_data";
char sipNm_jwdb_ams_sim_read_analog_x_y_data_complex[] = "ams_sim_read_analog_x_y_data_complex";
char sipNm_jwdb_ams_sim_read_analog_x_y_data[] = "ams_sim_read_analog_x_y_data";
char sipNm_jwdb_ams_read_selected_digital_waves[] = "ams_read_selected_digital_waves";
char sipNm_jwdb_ams_read_selected_waves_complex[] = "ams_read_selected_waves_complex";
char sipNm_jwdb_ams_read_selected_waves[] = "ams_read_selected_waves";
char sipNm_jwdb_ams_sim_set_simulation_read_stop[] = "ams_sim_set_simulation_read_stop";
char sipNm_jwdb_ams_sim_set_simulation_read_start[] = "ams_sim_set_simulation_read_start";
char sipNm_jwdb_ams_sim_is_wave_digital[] = "ams_sim_is_wave_digital";
char sipNm_jwdb_ams_sim_is_wave_analog[] = "ams_sim_is_wave_analog";
char sipNm_jwdb_ams_sim_is_wave_complex[] = "ams_sim_is_wave_complex";
char sipNm_jwdb_ams_sim_get_wave_unit_name[] = "ams_sim_get_wave_unit_name";
char sipNm_jwdb_ams_sim_is_analog_wave[] = "ams_sim_is_analog_wave";
char sipNm_jwdb_ams_sim_get_index_to_extract_waveform[] = "ams_sim_get_index_to_extract_waveform";
char sipNm_jwdb_ams_sim_get_next_waveform_name[] = "ams_sim_get_next_waveform_name";
char sipNm_jwdb_ams_sim_get_next_waveform_index[] = "ams_sim_get_next_waveform_index";
char sipNm_jwdb_ams_sim_get_simulation_parameter_info[] = "ams_sim_get_simulation_parameter_info";
char sipNm_jwdb_ams_sim_get_simulation_parameter_number[] = "ams_sim_get_simulation_parameter_number";
char sipNm_jwdb_ams_sim_get_creation_time[] = "ams_sim_get_creation_time";
char sipNm_jwdb_ams_sim_get_creation_date[] = "ams_sim_get_creation_date";
char sipNm_jwdb_ams_sim_get_x_unit_name[] = "ams_sim_get_x_unit_name";
char sipNm_jwdb_ams_sim_set_simulation_xstop[] = "ams_sim_set_simulation_xstop";
char sipNm_jwdb_ams_sim_set_simulation_xstart[] = "ams_sim_set_simulation_xstart";
char sipNm_jwdb_ams_sim_load_simu_with_complex_by_index[] = "ams_sim_load_simu_with_complex_by_index";
char sipNm_jwdb_ams_sim_load_simu_with_complex[] = "ams_sim_load_simu_with_complex";
char sipNm_jwdb_ams_sim_load_simu_by_index[] = "ams_sim_load_simu_by_index";
char sipNm_jwdb_ams_sim_load_simu[] = "ams_sim_load_simu";
char sipNm_jwdb_ams_sim_is_compat_file[] = "ams_sim_is_compat_file";
char sipNm_jwdb_ams_sim_is_cou_file[] = "ams_sim_is_cou_file";
char sipNm_jwdb_ams_sim_is_wdb_file[] = "ams_sim_is_wdb_file";
char sipNm_jwdb_ams_sim_is_jwdb_file[] = "ams_sim_is_jwdb_file";
char sipNm_jwdb_ams_sim_open_read_file[] = "ams_sim_open_read_file";
char sipNm_jwdb_ams_sim_set_jwdb_server[] = "ams_sim_set_jwdb_server";
char sipNm_jwdb_ams_sim_set_multirun_mode[] = "ams_sim_set_multirun_mode";
char sipNm_jwdb_ams_sim_set_data_blocksize[] = "ams_sim_set_data_blocksize";
char sipNm_jwdb_ams_sim_set_connection_message[] = "ams_sim_set_connection_message";
char sipNm_jwdb_ams_sim_init_file[] = "ams_sim_init_file";
#line 4 "jwdb.sip"
#include <ams_sim.h>
#include <malloc.h>

/* Wrapper for function that needs allocation of strings etc */
char ams_sim_get_simulation_parameter_info_wrapper   (long index, long iparam, char **name, char **val) {
  /* Allocate buffers */
  *name = malloc(LINE);
  *val = malloc(LINE);
  return ams_sim_get_simulation_parameter_info(index,iparam,*name,*val);
}  
long ams_sim_get_next_waveform_name_wrapper (long index, char ** dest, long from_where) {
  /* Allocate buffers */
  *dest = malloc(LINE);
  return ams_sim_get_next_waveform_name(index,*dest, from_where);
}   

#line 73 "sipjwdbcmodule.c"


static PyObject *func_ams_sim_read_digital_x_y_data_v1(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;
        double a2;
        char * a3;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_read_digital_x_y_data_v1(a0,a1,&a2,&a3);

            return sipBuildResult(0,"(lds)",sipRes,a2,a3);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_read_digital_x_y_data_v1);

    return NULL;
}


static PyObject *func_ams_sim_read_analog_x_y_data_v1(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;
        double a2;
        double a3;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_read_analog_x_y_data_v1(a0,a1,&a2,&a3);

            return sipBuildResult(0,"(ldd)",sipRes,a2,a3);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_read_analog_x_y_data_v1);

    return NULL;
}


static PyObject *func_ams_sim_close_read_file(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            ams_sim_close_read_file(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_close_read_file);

    return NULL;
}


static PyObject *func_ams_sim_get_digital_x_y_data(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;
        double a2;
        char * a3;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_get_digital_x_y_data(a0,a1,&a2,&a3);

            return sipBuildResult(0,"(lds)",sipRes,a2,a3);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_get_digital_x_y_data);

    return NULL;
}


static PyObject *func_ams_sim_get_analog_x_y_data(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;
        double a2;
        double a3;
        double a4;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_get_analog_x_y_data(a0,a1,&a2,&a3,&a4);

            return sipBuildResult(0,"(lddd)",sipRes,a2,a3,a4);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_get_analog_x_y_data);

    return NULL;
}


static PyObject *func_ams_sim_get_x_data(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        double a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            long sipRes;

            sipRes = ams_sim_get_x_data(a0,&a1);

            return sipBuildResult(0,"(ld)",sipRes,a1);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_get_x_data);

    return NULL;
}


static PyObject *func_ams_sim_read_mixed_x_y_data(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            long sipRes;

            sipRes = ams_sim_read_mixed_x_y_data(a0);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_read_mixed_x_y_data);

    return NULL;
}


static PyObject *func_ams_sim_read_digital_x_y_data(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;
        double a2;
        char * a3;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_read_digital_x_y_data(a0,a1,&a2,&a3);

            return sipBuildResult(0,"(lds)",sipRes,a2,a3);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_read_digital_x_y_data);

    return NULL;
}


static PyObject *func_ams_sim_read_analog_x_y_data_complex(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;
        double a2;
        double a3;
        double a4;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_read_analog_x_y_data_complex(a0,a1,&a2,&a3,&a4);

            return sipBuildResult(0,"(lddd)",sipRes,a2,a3,a4);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_read_analog_x_y_data_complex);

    return NULL;
}


static PyObject *func_ams_sim_read_analog_x_y_data(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;
        double a2;
        double a3;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_read_analog_x_y_data(a0,a1,&a2,&a3);

            return sipBuildResult(0,"(ldd)",sipRes,a2,a3);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_read_analog_x_y_data);

    return NULL;
}


static PyObject *func_ams_read_selected_digital_waves(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;
        long a2;
        double a3;
        char * a4;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a2))
        {
            long sipRes;

            sipRes = ams_read_selected_digital_waves(a0,&a1,a2,&a3,&a4);

            return sipBuildResult(0,"(llds)",sipRes,a1,a3,a4);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_read_selected_digital_waves);

    return NULL;
}


static PyObject *func_ams_read_selected_waves_complex(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;
        long a2;
        double a3;
        double a4;
        double a5;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a2))
        {
            long sipRes;

            sipRes = ams_read_selected_waves_complex(a0,&a1,a2,&a3,&a4,&a5);

            return sipBuildResult(0,"(llddd)",sipRes,a1,a3,a4,a5);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_read_selected_waves_complex);

    return NULL;
}


static PyObject *func_ams_read_selected_waves(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;
        long a2;
        double a3;
        double a4;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a2))
        {
            long sipRes;

            sipRes = ams_read_selected_waves(a0,&a1,a2,&a3,&a4);

            return sipBuildResult(0,"(lldd)",sipRes,a1,a3,a4);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_read_selected_waves);

    return NULL;
}


static PyObject *func_ams_sim_set_simulation_read_stop(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        double a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ld",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_set_simulation_read_stop(a0,a1);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_set_simulation_read_stop);

    return NULL;
}


static PyObject *func_ams_sim_set_simulation_read_start(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        double a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ld",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_set_simulation_read_start(a0,a1);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_set_simulation_read_start);

    return NULL;
}


static PyObject *func_ams_sim_is_wave_digital(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            char sipRes;

            sipRes = ams_sim_is_wave_digital(a0,a1);

            return PyString_FromStringAndSize(&sipRes,1);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_is_wave_digital);

    return NULL;
}


static PyObject *func_ams_sim_is_wave_analog(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            char sipRes;

            sipRes = ams_sim_is_wave_analog(a0,a1);

            return PyString_FromStringAndSize(&sipRes,1);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_is_wave_analog);

    return NULL;
}


static PyObject *func_ams_sim_is_wave_complex(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            char sipRes;

            sipRes = ams_sim_is_wave_complex(a0,a1);

            return PyString_FromStringAndSize(&sipRes,1);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_is_wave_complex);

    return NULL;
}


static PyObject *func_ams_sim_get_wave_unit_name(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            char *sipRes;

            sipRes = ams_sim_get_wave_unit_name(a0,a1);

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return PyString_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_get_wave_unit_name);

    return NULL;
}


static PyObject *func_ams_sim_is_analog_wave(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        char * a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"s",&a0))
        {
            int sipRes;

            sipRes = ams_sim_is_analog_wave(a0);

            return PyInt_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_is_analog_wave);

    return NULL;
}


static PyObject *func_ams_sim_get_index_to_extract_waveform(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        char * a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ls",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_get_index_to_extract_waveform(a0,a1);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_get_index_to_extract_waveform);

    return NULL;
}


static PyObject *func_ams_sim_get_next_waveform_name(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        char * a1;
        long a2;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a2))
        {
            long sipRes;

            sipRes = ams_sim_get_next_waveform_name_wrapper(a0,&a1,a2);

            return sipBuildResult(0,"(ls)",sipRes,a1);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_get_next_waveform_name);

    return NULL;
}


static PyObject *func_ams_sim_get_next_waveform_index(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_get_next_waveform_index(a0,a1);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_get_next_waveform_index);

    return NULL;
}


static PyObject *func_ams_sim_get_simulation_parameter_info(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;
        char * a2;
        char * a3;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            char sipRes;

            sipRes = ams_sim_get_simulation_parameter_info_wrapper(a0,a1,&a2,&a3);

            return sipBuildResult(0,"(css)",sipRes,a2,a3);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_get_simulation_parameter_info);

    return NULL;
}


static PyObject *func_ams_sim_get_simulation_parameter_number(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            long sipRes;

            sipRes = ams_sim_get_simulation_parameter_number(a0);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_get_simulation_parameter_number);

    return NULL;
}


static PyObject *func_ams_sim_get_creation_time(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            char *sipRes;

            sipRes = ams_sim_get_creation_time(a0);

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return PyString_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_get_creation_time);

    return NULL;
}


static PyObject *func_ams_sim_get_creation_date(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            char *sipRes;

            sipRes = ams_sim_get_creation_date(a0);

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return PyString_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_get_creation_date);

    return NULL;
}


static PyObject *func_ams_sim_get_x_unit_name(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            char *sipRes;

            sipRes = ams_sim_get_x_unit_name(a0);

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return PyString_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_get_x_unit_name);

    return NULL;
}


static PyObject *func_ams_sim_set_simulation_xstop(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        double a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ld",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_set_simulation_xstop(a0,a1);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_set_simulation_xstop);

    return NULL;
}


static PyObject *func_ams_sim_set_simulation_xstart(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        double a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ld",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_set_simulation_xstart(a0,a1);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_set_simulation_xstart);

    return NULL;
}


static PyObject *func_ams_sim_load_simu_with_complex_by_index(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_load_simu_with_complex_by_index(a0,a1);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_load_simu_with_complex_by_index);

    return NULL;
}


static PyObject *func_ams_sim_load_simu_with_complex(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            long sipRes;

            sipRes = ams_sim_load_simu_with_complex(a0);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_load_simu_with_complex);

    return NULL;
}


static PyObject *func_ams_sim_load_simu_by_index(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;
        long a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"ll",&a0,&a1))
        {
            long sipRes;

            sipRes = ams_sim_load_simu_by_index(a0,a1);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_load_simu_by_index);

    return NULL;
}


static PyObject *func_ams_sim_load_simu(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            long sipRes;

            sipRes = ams_sim_load_simu(a0);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_load_simu);

    return NULL;
}


static PyObject *func_ams_sim_is_compat_file(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            char sipRes;

            sipRes = ams_sim_is_compat_file(a0);

            return PyString_FromStringAndSize(&sipRes,1);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_is_compat_file);

    return NULL;
}


static PyObject *func_ams_sim_is_cou_file(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            char sipRes;

            sipRes = ams_sim_is_cou_file(a0);

            return PyString_FromStringAndSize(&sipRes,1);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_is_cou_file);

    return NULL;
}


static PyObject *func_ams_sim_is_wdb_file(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            char sipRes;

            sipRes = ams_sim_is_wdb_file(a0);

            return PyString_FromStringAndSize(&sipRes,1);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_is_wdb_file);

    return NULL;
}


static PyObject *func_ams_sim_is_jwdb_file(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            char sipRes;

            sipRes = ams_sim_is_jwdb_file(a0);

            return PyString_FromStringAndSize(&sipRes,1);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_is_jwdb_file);

    return NULL;
}


static PyObject *func_ams_sim_open_read_file(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        char * a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"s",&a0))
        {
            long sipRes;

            sipRes = ams_sim_open_read_file(a0);

            return PyLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_open_read_file);

    return NULL;
}


static PyObject *func_ams_sim_set_jwdb_server(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        char * a0;
        long a1;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"sl",&a0,&a1))
        {
            ams_sim_set_jwdb_server(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_set_jwdb_server);

    return NULL;
}


static PyObject *func_ams_sim_set_multirun_mode(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        char a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"c",&a0))
        {
            ams_sim_set_multirun_mode(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_set_multirun_mode);

    return NULL;
}


static PyObject *func_ams_sim_set_data_blocksize(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        long a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"l",&a0))
        {
            ams_sim_set_data_blocksize(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_set_data_blocksize);

    return NULL;
}


static PyObject *func_ams_sim_set_connection_message(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        char a0;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"c",&a0))
        {
            ams_sim_set_connection_message(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_set_connection_message);

    return NULL;
}


static PyObject *func_ams_sim_init_file(PyObject *sipSelf,PyObject *sipArgs)
{
    int sipArgsParsed = 0;

    {
        if (sipParseArgs(&sipArgsParsed,sipArgs,""))
        {
            ams_sim_init_file();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipArgsParsed,sipNm_jwdb_ams_sim_init_file);

    return NULL;
}


/* This defines this module. */
sipExportedModuleDef sipModuleAPI_jwdb = {
    NULL,
    SIP_API_MINOR_NR,
    "jwdb",
    NULL,
    0,
    NULL,
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
};


/* The SIP API and the APIs of any imported modules. */
const sipAPIDef *sipAPI_jwdb;


/* The Python module initialisation function. */
#if defined(SIP_STATIC_MODULE)
void initjwdb()
#else
PyMODINIT_FUNC initjwdb()
#endif
{
    static PyMethodDef sip_methods[] = {
        {sipNm_jwdb_ams_sim_read_digital_x_y_data_v1, func_ams_sim_read_digital_x_y_data_v1, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_read_analog_x_y_data_v1, func_ams_sim_read_analog_x_y_data_v1, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_close_read_file, func_ams_sim_close_read_file, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_get_digital_x_y_data, func_ams_sim_get_digital_x_y_data, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_get_analog_x_y_data, func_ams_sim_get_analog_x_y_data, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_get_x_data, func_ams_sim_get_x_data, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_read_mixed_x_y_data, func_ams_sim_read_mixed_x_y_data, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_read_digital_x_y_data, func_ams_sim_read_digital_x_y_data, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_read_analog_x_y_data_complex, func_ams_sim_read_analog_x_y_data_complex, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_read_analog_x_y_data, func_ams_sim_read_analog_x_y_data, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_read_selected_digital_waves, func_ams_read_selected_digital_waves, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_read_selected_waves_complex, func_ams_read_selected_waves_complex, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_read_selected_waves, func_ams_read_selected_waves, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_set_simulation_read_stop, func_ams_sim_set_simulation_read_stop, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_set_simulation_read_start, func_ams_sim_set_simulation_read_start, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_is_wave_digital, func_ams_sim_is_wave_digital, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_is_wave_analog, func_ams_sim_is_wave_analog, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_is_wave_complex, func_ams_sim_is_wave_complex, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_get_wave_unit_name, func_ams_sim_get_wave_unit_name, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_is_analog_wave, func_ams_sim_is_analog_wave, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_get_index_to_extract_waveform, func_ams_sim_get_index_to_extract_waveform, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_get_next_waveform_name, func_ams_sim_get_next_waveform_name, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_get_next_waveform_index, func_ams_sim_get_next_waveform_index, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_get_simulation_parameter_info, func_ams_sim_get_simulation_parameter_info, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_get_simulation_parameter_number, func_ams_sim_get_simulation_parameter_number, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_get_creation_time, func_ams_sim_get_creation_time, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_get_creation_date, func_ams_sim_get_creation_date, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_get_x_unit_name, func_ams_sim_get_x_unit_name, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_set_simulation_xstop, func_ams_sim_set_simulation_xstop, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_set_simulation_xstart, func_ams_sim_set_simulation_xstart, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_load_simu_with_complex_by_index, func_ams_sim_load_simu_with_complex_by_index, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_load_simu_with_complex, func_ams_sim_load_simu_with_complex, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_load_simu_by_index, func_ams_sim_load_simu_by_index, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_load_simu, func_ams_sim_load_simu, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_is_compat_file, func_ams_sim_is_compat_file, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_is_cou_file, func_ams_sim_is_cou_file, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_is_wdb_file, func_ams_sim_is_wdb_file, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_is_jwdb_file, func_ams_sim_is_jwdb_file, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_open_read_file, func_ams_sim_open_read_file, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_set_jwdb_server, func_ams_sim_set_jwdb_server, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_set_multirun_mode, func_ams_sim_set_multirun_mode, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_set_data_blocksize, func_ams_sim_set_data_blocksize, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_set_connection_message, func_ams_sim_set_connection_message, METH_VARARGS, NULL},
        {sipNm_jwdb_ams_sim_init_file, func_ams_sim_init_file, METH_VARARGS, NULL},
        {0, 0, 0, 0}
    };

    PyObject *sipModule, *sipModuleDict;
    PyObject *sip_sipmod, *sip_capiobj;

    /* Initialise the module and get it's dictionary. */
    sipModule = Py_InitModule((char *)sipModuleAPI_jwdb.em_name,sip_methods);
    sipModuleDict = PyModule_GetDict(sipModule);

    /* Import the SIP module and get it's API. */
#if PY_VERSION_HEX >= 0x02050000
    sip_sipmod = PyImport_ImportModule("sip");
#else
    sip_sipmod = PyImport_ImportModule((char *)"sip");
#endif

    if (sip_sipmod == NULL)
        return;

    sip_capiobj = PyDict_GetItemString(PyModule_GetDict(sip_sipmod), "_C_API");

    if (sip_capiobj == NULL || !PyCObject_Check(sip_capiobj))
        return;

    sipAPI_jwdb = (const sipAPIDef *)PyCObject_AsVoidPtr(sip_capiobj);

    /* Export the module and publish it's API. */
    if (sipAPI_jwdb->api_export_module(&sipModuleAPI_jwdb,SIP_API_MAJOR_NR,SIP_API_MINOR_NR,sipModuleDict) < 0)
       return;
}
