#!/usr/bin/env python
import shutil
import sys
import tempfile
import pycircuit.post.cds.cds as cds
import pycircuit.post.cds.netlist as netlist

from optparse import OptionParser, BadOptionError, OptionValueError

version = '0.0'
    
usage = 'usage: %prog [options] library cell [view]'

parser = OptionParser(usage=usage,
                      version=version,
                      prog='cdsnetlist',
                      description='Cadence Virtuoso netlister')

(options, args) = parser.parse_args()

if len(args) < 2:
    parser.error("incorrect number of arguments")

lib, cell = args[:2]

if len(args) > 2:
    view = args[2]
else:
    view = 'schematic'

targetdir = tempfile.mkdtemp()
remove_targetdir_after = True

try:
    session = cds.CadenceSession()
    result = netlist.netlist_cell(session, lib, cell, view)
    
    print open(result["netlist_filename"], "r").read()

finally:
    if remove_targetdir_after:
        shutil.rmtree(targetdir)



    
