"""Production compact models written in the Behavioural DSL.

`elements_hdl.py` re-expresses the classical elements to prove the DSL
equals `elements.py`.  This module is the other direction: real foundry
compact models, translated from their shipped Verilog-A and checked
against the vendor's own compiled binary.

The reference data lives in `tests/data/` and is generated by the
scripts in `benchmarks/` from the IHP Open PDK (SG13G2), which ships
Verilog-A sources, compiled OSDI binaries and extracted model cards.

Currently: `CapCmomi`.
"""

import numpy as np
import sympy

from pycircuit.circuit import (defaultepar, juncap, psp_kernel,
                               psp_scaling)
from pycircuit.circuit.constants import (epsRSiO2, kboltzmann,
                                         qelectron)
from pycircuit.circuit.hdl import (Behavioural, Branch, Collapse,
                                   Contribution, Node,
                                   flicker_noise, white_noise,
                                   ddt, var, vt)
from pycircuit.utilities.param import Parameter


#: Permittivities, from the toolkit's own constants so a generated stamp
#: matches a hand-written one exactly rather than nearly.
## PSP's own constants, not the tree's -- see the note beside them in
## `psp_scaling`.  `EPSRSI` is 11.8 in the vendor source against 11.7 in
## `pycircuit.circuit.constants`, and the 0.43% that puts on the body
## factor was worth 2-6 mV of threshold: the last residual on this
## model, and the one thing standing between thirty-one exactly-matched
## parameters and the current.
EPS0 = psp_scaling.PSP_EPS0
EPS_SI = psp_scaling.PSP_EPS_SI
QELE = psp_scaling.PSP_QELE

## `vt()` is the DSL's thermal voltage and is built on the tree's
## constants, which is right for the tree and wrong for a comparison
## against PSP.  Correcting it by a constant ratio keeps its temperature
## dependence -- which is the part that has to come from the simulator
## -- while putting it on PSP's `KBOL` and `QELE`.  Worth 0.035%.
_VT_TO_PSP = ((psp_scaling.PSP_KBOL / kboltzmann)
              * (qelectron / psp_scaling.PSP_QELE))

#: 1/sqrt(2), as PSP spells it.
INV_SQRT2 = 7.0710678118654746e-01


#: Weak anchor conductance so a floating port or internal island never
#: gives a singular matrix.  The vendor's ``GLEAK``.  Module level, not a
#: class attribute: `analog()` runs while the class body is still being
#: executed, so the class name does not exist yet.
GLEAK = 1.0e-12


def _sel(pairs, default):
    """A parameter-keyed selection, as Verilog-A's nested ``? :``.

    ``pairs`` is ``[(condition, value), ...]`` tried in order.  Written
    as one `Piecewise` rather than nested ones so the compiled `select`
    is flat, and so the fall-through is visible in one place.
    """
    return sympy.Piecewise(*([(v, c) for c, v in pairs] + [(default, True)]))


class CapCmomi(Behavioural):
    """Interdigitated metal-oxide-metal capacitor -- IHP ``cap_cmomi``.

    Translated from ``ihp-sg13g2/libs.tech/verilog-a/cap_cmomi/cap_cmomi.va``
    (314 lines).  An EM-fitted RF equivalent circuit:

    .. code-block:: text

        PLUS --(Lskin || Rskin)-- Cmain --(Lcore)--(Rseries)-- MINUS
                                              |
                                             Cox      (shunt off the MINUS side)
                                              |
                                        (Rsub || Csub)
                                              |
                                             SUB

    Every coefficient is selected by the metal LAYER COUNT
    ``N = mmax - mmin + 1`` (and, for the oxide shunt, by the bottom-metal
    index), and the core inductance is keyed by feed style: ``feed=double``
    takes the two-sided loop fit, ``same``/``none`` recover the much
    smaller single-side inductance from the model's own capacitance and a
    fitted self-resonance.  The comments below record only what the
    translation had to decide; the physics provenance is in the vendor
    header.

    ``$mfactor`` is deliberately not applied.  The vendor model reads it
    but does NOT scale its elements by it -- the simulator multiplies the
    device stamps by ``m`` itself, and scaling here too would give ``m**2``.
    The vendor source says so in a comment; see hdl.md Phase E.

    Verified against the PDK's own OSDI build over 1 MHz - 100 GHz for ten
    configurations covering every coefficient branch
    (`test_compact_cap_cmomi.py`, reference generated by
    `benchmarks/cap_cmomi_reference.py`).
    """

    instparams = [
        Parameter(name='w', desc='Width (Y, row stacking)', unit='m',
                  default=5e-6),
        Parameter(name='l', desc='Length (X, finger length)', unit='m',
                  default=5e-6),
        Parameter(name='mmin', desc='Bottom metal index', unit='',
                  default=1),
        Parameter(name='mmax', desc='Top metal index', unit='', default=5),
        Parameter(name='feed', desc='Feed code: 0=none 1=same 2=double',
                  unit='', default=2),
        Parameter(name='subblock', desc='Substrate-isolation block '
                  '(layout/LVS only, no electrical effect)', unit='',
                  default=0),
    ]

    @staticmethod
    def analog(PLUS, MINUS, SUB):
        nsk, ncap, nl, nox = (Node('nsk'), Node('ncap'), Node('nl'),
                              Node('nox'))

        ## Eight NAMED branches, three pairs of which share a node pair:
        ## the skin arm is an inductor in parallel with a resistor, and
        ## the substrate termination is a resistor in parallel with a
        ## capacitor.  Anonymous branches would merge each pair into one
        ## unknown and lose a constitutive relation.
        br_lskin = Branch(PLUS, nsk, 'lskin')
        br_rskin = Branch(PLUS, nsk, 'rskin')
        br_cmain = Branch(nsk, ncap, 'cmain')
        br_lcore = Branch(ncap, nl, 'lcore')
        br_rser = Branch(nl, MINUS, 'rser')
        br_cox = Branch(nl, nox, 'cox')
        br_rsub = Branch(nox, SUB, 'rsub')
        br_csub = Branch(nox, SUB, 'csub')
        br_lkp = Branch(PLUS, SUB, 'lkp')
        br_lkm = Branch(MINUS, SUB, 'lkm')

        ## Parameters arrive in SI; the fits are all in micrometres.
        lu = l * 1e6                                          # noqa: F821
        wu = w * 1e6                                          # noqa: F821
        lw = wu + lu
        ratio = lu / wu

        Nlay = sympy.Max(mmax - mmin + 1, 1)                  # noqa: F821

        ## Unit-cell tiling, 0.84 x 0.89 um, one y-row spent on the feed.
        ## The epsilon before the floor is the vendor's, and it is load-
        ## bearing: a drawn dimension that is an exact multiple of the
        ## pitch round-trips through *1e6 to one ulp below the integer,
        ## and floor() would then land on k or k-1 depending on whether
        ## the backend divides or multiplies by the reciprocal.  The
        ## model must agree with the PCell layout for every geometry, so
        ## the nudge (1e-6 cell = 0.84 pm, far below any layout grid)
        ## makes an exact k-pitch resolve to k everywhere.
        ax = sympy.floor(lu / 0.84 + 1e-6)
        ay = sympy.floor(wu / 0.89 + 1e-6) - 1
        active_x = sympy.Max(ax, 1)
        active_y = sympy.Max(ay, 1)
        active_area = active_x * active_y * 0.84 * 0.89
        feed_width = active_y * 0.89 + 0.64

        issame = _sel([(sympy.Eq(feed, 1), 1.0)], 0.0)         # noqa: F821

        ## Area density [fF/um^2] and single-side feed cap [fF/um] by N.
        density = _sel([(Nlay <= 2, 0.55),
                        (sympy.Eq(Nlay, 3), 0.82),
                        (sympy.Eq(Nlay, 4), 1.09)], 1.36)
        cfeed_pu = _sel([(Nlay <= 2, 0.70),
                         (sympy.Eq(Nlay, 3), 0.97),
                         (sympy.Eq(Nlay, 4), 1.28)], 1.46)

        cfeed_fF = issame * cfeed_pu * feed_width
        cmain_fF = density * active_area + cfeed_fF
        Cmain = cmain_fF * 1e-15

        ## Series resistance [ohm].  'same' is layer-independent; 'none'
        ## reuses the opposite-side set, which is the vendor's choice.
        Rseries = _sel(
            [(issame > 0.5, 0.22 + 0.40 * ratio),
             (Nlay <= 3, 0.10 + 0.31 * ratio),
             (sympy.Eq(Nlay, 4), 0.14 + 0.27 * ratio)],
            0.15 + 0.26 * ratio)
        Rseries = sympy.Max(Rseries, 1e-3)

        ## Core inductance, keyed by FEED.  feed=double is a real loop
        ## (current down one comb and back the other) worth tens of pH;
        ## same/none have no such loop, and their much smaller local
        ## inductance is recovered from this model's own Cmain and the
        ## fitted single-side self-resonance.
        srf_ss = _sel([(Nlay <= 3, 1e9 / (7.68e-5 + 6.64e-5 * lu)),
                       (sympy.Eq(Nlay, 4), 1e9 / (8.82e-4 + 4.72e-5 * lu))],
                      1e9 / (2.85e-4 + 6.87e-5 * lu))
        wsrf = 2 * sympy.pi * srf_ss
        Lcore = _sel(
            [(sympy.Eq(feed, 2),                              # noqa: F821
              (4.886 + 3.117 * ratio + 0.510 * lu
               - 2.526 * sympy.sqrt(lu)) * 1e-12)],
            1.0 / (wsrf * wsrf * Cmain))
        Lcore = sympy.Max(Lcore, 1e-18)

        ## Skin effect.
        Rskin1 = _sel([(Nlay <= 3, 0.031)], 0.035)
        Lskin_c = _sel([(Nlay <= 3, 0.214)], 0.010)
        Lskin_s = _sel([(Nlay <= 3, 0.02256)], 0.0626)
        Rskin = sympy.Max(Rskin1 * lu, 1e-3)
        Lskin = (Lskin_c + Lskin_s * lu) * 1e-12

        ## Oxide capacitance, keyed by the BOTTOM metal index -- the
        ## vendor's re-keying of coefficient sets the source notes index
        ## by layer count.
        cox0 = _sel([(sympy.Eq(mmin, 1), 1.725),              # noqa: F821
                     (sympy.Eq(mmin, 2), 1.240)], 1.052)      # noqa: F821
        cox1 = _sel([(sympy.Eq(mmin, 1), 0.1192),             # noqa: F821
                     (sympy.Eq(mmin, 2), 0.1139)], 0.09867)   # noqa: F821
        cox2 = _sel([(sympy.Eq(mmin, 1), 0.019406),           # noqa: F821
                     (sympy.Eq(mmin, 2), 0.011417)], 0.011364)  # noqa
        Cox = (cox0 + cox1 * lw + cox2 * wu * lu) * 1e-15

        Rsub = sympy.Max(3144.0 - 9.6942 * lw + 0.0207848 * wu * lu, 1e-2)
        Csub = (9.8833 + 0.089195 * lw + 0.000675931 * wu * lu) * 1e-15

        return (
            ## Skin arm: inductor (voltage-defined) || resistor.
            Contribution(br_lskin.V, ddt(Lskin * br_lskin.I)),
            Contribution(br_rskin.I, br_rskin.V / Rskin),
            ## Main capacitance, core inductance, series resistance.
            Contribution(br_cmain.I, ddt(Cmain * br_cmain.V)),
            Contribution(br_lcore.V, ddt(Lcore * br_lcore.I)),
            Contribution(br_rser.I, br_rser.V / Rseries),
            ## Substrate shunt: Cox in series with Rsub || Csub.
            Contribution(br_cox.I, ddt(Cox * br_cox.V)),
            Contribution(br_rsub.I, br_rsub.V / Rsub),
            Contribution(br_csub.I, ddt(Csub * br_csub.V)),
            ## Weak DC anchors, so a floating port or island never leaves
            ## the matrix singular.
            Contribution(br_lkp.I, GLEAK * br_lkp.V),
            Contribution(br_lkm.I, GLEAK * br_lkm.V),
        )


def _psp_mos_analog(T, pmos):
    """Build the analog body for one channel type.

    PSP is written once and run for both polarities, and it does not do
    that with a symbolic sign.  `CHNL_TYPE` is fixed once in
    `INITIAL_MODEL` (`PSP103_module.include:557-561`), the terminal
    voltages are converted to an internal n-like convention on the way
    in (`:1035-1048`), every equation downstream is written for that
    convention alone, and the polarity is restored on every
    contribution on the way out (`:1697-1795`).

    Same here, and for the same reason: `T` and `pmos` are Python
    values closed over at class-creation time, so each channel type
    compiles to an expression exactly the size it would be if the other
    did not exist.  A symbolic polarity would double every branch in
    the model, and branch on something that cannot vary with bias.

    Only FIVE things genuinely differ between the two devices, and four
    of them are in the kernel -- the effective-field weighting at both
    channel ends, and the two velocity-saturation forms, holes
    following `v ~ E/(1 + E/Ec)` where electrons follow
    `v ~ E/sqrt(1 + (E/Ec)^2)`.  The fifth is the quantum-mechanical
    constant, in the scaling layer.  Everything else here is a sign.
    """
    def analog(d, g, s, b):
        ## GATE RESISTANCE, on an internal node behind a collapsible
        ## resistor -- which is exactly how PSP attaches it
        ## (`CollapsableR(ggate, RG_i, ..., G, GP, "rgate")`,
        ## `PSP103_module.include:1718`), and exactly what `Collapse()`
        ## was built for on this branch.  With `rg = 0` the node is
        ## absorbed and the branch never compiles, so the `1/rg` below is
        ## safe.  Everything intrinsic hangs off `gi`, not `g`.
        gi = Node('gi')
        br_rg = Branch(g, gi, 'rgate')

        bd, bg, bs = Branch(d, b, 'd'), Branch(gi, b, 'g'), Branch(s, b, 's')

        ## The INTERNAL convention: every voltage below is `T*(node -
        ## bulk)`, so for a p-channel the whole body runs on
        ## positive-for-conducting quantities exactly as the n-channel
        ## does.  `T` is restored on the contributions at the end.
        vdb = var(T * bd.V, 'vdb')
        vgb = var(T * bg.V, 'vgb')
        vsb = var(T * bs.V, 'vsb')

        ## Two thermal voltages, deliberately.  The BODY FACTOR is built
        ## on the plain one -- PSP's `G_0` is, and it only moves to the
        ## effective one under `SWFIX`, which defaults off.  Everything
        ## else -- gate drive, quasi-Fermi levels, charges, the current --
        ## is in units of the effective one.
        phit0 = var(vt() * _VT_TO_PSP, 'phit0')
        phit = var(phit0 * (1.0 + ct), 'phit')                # noqa: F821
        ## Oxide capacitance per unit area, and the body factor that
        ## follows from it.  `Gf` is gamma normalised by sqrt(phit),
        ## which is the form the surface-potential solver takes.
        ## The dielectric constant comes from the CARD, not from a
        ## module constant.  `psp_scaling` already reads `EPSROXO`
        ## (`PSP103_parlist.include:257`); the element used to hardcode
        ## the tree's 3.9, so the two agreed only by luck -- on a card
        ## with a different gate dielectric the scaling layer and the
        ## element would have disagreed about `cox`, silently, and that
        ## is the body factor AND the oxide capacitance.  Both are 3.9
        ## on this process, so nothing measurable moves; the point is
        ## that it is no longer a coincidence.
        cox = var(epsrox * EPS0 / tox, 'cox')                 # noqa: F821
        gamma = var(sympy.sqrt(2.0 * QELE * EPS_SI * nsub)    # noqa: F821
                    / cox, 'gamma')
        ## BIAS-DEPENDENT BODY FACTOR (`macrodefs:478-484`).  The
        ## depletion charge a real device presents is not that of a
        ## uniformly doped substrate: a pocket implant makes the
        ## effective doping rise as the gate pulls the depletion edge
        ## deeper, so `Gf` grows with gate drive.  PSP writes it as
        ## `Gf = G_0*sqrt(1 + DNSUB*maxa(0, Vgb - VNSUB, NSLP))`, the
        ## smooth maximum keeping it inactive below the onset without
        ## putting a corner there.
        ##
        ## `DNSUB` is 4.4e-16 on this PDK's n-channel card and 0.0397 on
        ## its p-channel one -- the third term here that a zero
        ## coefficient hides from any measurement made on one channel
        ## type alone.
        g0 = var(gamma / sympy.sqrt(phit0), 'g0')
        dns = var(dnsub * psp_kernel.maxa(vgb - vnsub, 0.0,  # noqa: F821
                                          nslp), 'dns')      # noqa: F821
        Gf = var(g0 * sympy.sqrt(1.0 + dns), 'Gf')
        xi = var(1.0 + Gf * INV_SQRT2, 'xi')

        ## Normalised gate drive, and the quasi-Fermi levels at the two
        ## channel ends.  Everything is referred to the bulk, which is
        ## what keeps source and drain interchangeable.

        beta = var(u0 * cox * w / l, 'beta')                  # noqa: F821

        ## SYMMETRISED BIAS VARIABLES.
        ##
        ## The intrinsic core is exactly antisymmetric under exchanging
        ## source and drain because every quantity it uses is either a
        ## midpoint one (even) or `dps` (odd).  The layers on top are not
        ## automatically so: the series resistance reads a source-bulk
        ## voltage and channel-length modulation reads `Vds`, and under
        ## the exchange the first CHANGES and the second flips sign
        ## through a function that is not odd.  Both broke the symmetry,
        ## and neither was caught until a card supplied nonzero `rs` and
        ## `alp` -- they default to zero, so every earlier symmetry test
        ## had them switched off.
        ##
        ## PSP's answer is `Vsbx = Vsbstar + 0.5*(Vds - Vdsx)`
        ## (`PSP103_macrodefs.include:472`), which evaluates to the
        ## LOWER of the two junction voltages under either polarity, plus
        ## a smoothed `|Vds|`.  Same construction here: `vdsx` is a
        ## smooth `|Vds|` and `vsbx` follows PSP's formula, so both are
        ## even and the antisymmetry survives.
        ## CONDITIONING OF THE TERMINAL VOLTAGES
        ## (`PSP103_macrodefs.include:330-334, 1104-1105`).
        ##
        ## The surface-potential solver needs the junction bias to stay
        ## above roughly `-phib`; below that the quasi-Fermi level has
        ## passed the built-in potential and the formulation stops
        ## meaning anything.  The kernel used to enforce that with a hard
        ## `max(xn, 0)`, which is fine for the VALUE and poison for the
        ## Jacobian: the clamp freezes every conductance, so Newton
        ## arrives with no gradient telling it how to get back.  A
        ## two-transistor stack was enough to expose it -- both the old
        ## and the new device swing out past the clamp on the way to the
        ## solution, and only the one with a gradient there returns.
        ##
        ## PSP limits smoothly instead, and at the VOLTAGE rather than at
        ## `xn`: take the lower of the two junctions, clip it at
        ## `-0.95*phib` through `MINA`, and lift `Vsb` by whatever the
        ## clip removed.  `phix1` re-centres it so that at ordinary bias
        ## the whole construction shifts `Vsb` by ~1e-5 V and is
        ## invisible.
        phix = var(0.95 * phib, 'phix')                       # noqa: F821
        aphi = var(0.0025 * phib * phib, 'aphi')              # noqa: F821
        phix2 = var(0.5 * sympy.sqrt(aphi), 'phix2')
        phix1 = var(psp_kernel.mina(phix - phix2, 0.0, aphi), 'phix1')
        vlow = var(psp_kernel.mina(vdb, vsb, aphi) + phix, 'vlow')
        vsbst = var(vsb - psp_kernel.mina(vlow, 0.0, aphi) + phix1,
                    'vsbst')

        vds = var(vdb - vsb, 'vds')
        vdsx = var(2.0 * psp_kernel.hdl.hypsmooth(vds, 1e-4) - vds, 'vdsx')
        vsbx = var(vsbst + 0.5 * (vds - vdsx), 'vsbx')

        ## DRAIN-INDUCED BARRIER LOWERING
        ## (`PSP103_macrodefs.include:473-476`).  A short channel lets
        ## the drain field reach the source barrier and lower it, so the
        ## device turns on earlier at high drain bias.  PSP models it as
        ## a shift of the GATE DRIVE rather than of a threshold voltage
        ## -- there is no threshold voltage in a surface-potential model
        ## to shift.
        ##
        ## Built on the symmetrised `vdsx`/`vsbx`, so it is even under
        ## the source/drain exchange and cannot break the antisymmetry
        ## the way series resistance and channel-length modulation both
        ## did before them.  `CFD` is zero on this card, which makes
        ## `Vdsp = Vdsx`; the general form is kept because a card that
        ## sets it would otherwise be silently mismodelled.
        vdsp = var(2.0 * vdsx * psp_kernel.hdl.safe_div(
            1.0, 1.0 + psp_kernel.hdl.safe_sqrt(1.0 + cfd * vdsx),  # noqa
            eps=1e-30), 'vdsp')
        delvg = var(cf * vdsp * (1.0 + cfb * vsbx), 'delvg')  # noqa: F821

        ## `vgb`, NOT PSP's literal `Vgs + Vsbstar` (`macrodefs:470`).
        ## The two are the same quantity in PSP, because PSP evaluates
        ## that expression AFTER its source/drain interchange, so its
        ## `Vgs` is referred to the lower terminal.  Ours is referred to
        ## the actual source, which CHANGES under the exchange -- and
        ## writing it that way cost the exact antisymmetry immediately.
        ## The difference is the conditioning, a fraction of a millivolt,
        ## and it is not worth a structural property.
        xg = var((vgb - vfb + delvg) / phit, 'xg')            # noqa: F821

        ## ORDERED TERMINALS.
        ##
        ## The saturation-limited drain voltage broke what the paragraph
        ## above describes.  `Vdsat` is built from SOURCE-SIDE quantities
        ## alone -- the inversion charge and mobility at the low end of
        ## the channel -- so the core stopped being an odd function of
        ## `Vds`: swapping the terminals changed which end `Vdsat` was
        ## measured at, and the reverse current came out 16% larger.
        ##
        ## PSP does not solve this with a cleverer formula.  It orders
        ## the terminals, computes the device forward, and swaps the
        ## contributions on the way out.  Same here, using the
        ## symmetrised variables that already exist: `vsbx` IS the lower
        ## junction under either polarity, and `vdsx` is `|Vds|`.  So the
        ## core always sees a forward device, and the sign is applied
        ## afterwards.  The antisymmetry is now a property of the
        ## TOPOLOGY rather than of the algebra, which is the only form of
        ## it that survives adding non-odd physics.
        xn_s = var((phib + vsbx) / phit, 'xn_s')              # noqa: F821
        xn_d = var(xn_s + vdsx / phit, 'xn_d')

        ## A smooth sign of `Vds`.  `vdsx` is `sqrt(Vds^2 + 4e^2)`, so
        ## this is exactly +-1 away from the origin, is zero AT the
        ## origin, and never divides by zero (`vdsx >= 2e`).
        sgn = var(vds / vdsx, 'sgn')

        core = psp_kernel.intrinsic(
            xg, xn_s, xn_d, Gf, xi, phit, beta,
            mob=dict(mue=mue, themu=themu, cs=cs,          # noqa: F821
                     thecs=thecs, feta=feta, thesat=thesat,  # noqa: F821
                     rs=rs, rsg=rsg, rsb=rsb, vsb=vsbx,     # noqa: F821
                     alp=alp, vp=vp, vds=vdsx,              # noqa: F821
                     alp1=alp1, alp2=alp2, ax=ax,           # noqa: F821
                     thesatb=thesatb, thesatg=thesatg,  # noqa: F821
                     pmos=pmos, xcor=xcor,          # noqa: F821
                     kp=kp,                                 # noqa: F821
                     cox_area=cox, eps_si=EPS_SI))
        ## The total oxide capacitance the CHARGES see.  Two things
        ## separate it from `cox*w*l`, and together they were worth 24%:
        ## the CV effective dimensions, and the quantum-mechanical
        ## reduction applied inside `cox_qm` below.  Zero `wcv`/`lcv`
        ## means "no card said otherwise", so fall back to drawn.
        cox_tot = var(cox * sympy.Piecewise((wcv, wcv > 0.0), (w, True))
                      * sympy.Piecewise((lcv, lcv > 0.0), (l, True)),
                      'cox_tot')                              # noqa: F821
        cox_c = psp_kernel.cox_qm(core, cox_tot, qq, phit0,  # noqa: F821
                                  pmos=pmos)
        Qg, Qd, Qb = psp_kernel.charges_long_channel(core, xg, phit,
                                                     cox_c)

        ## The charges are contributed on branches referred to the
        ## SOURCE, exactly as PSP does it.  That makes
        ## `Qs = -(Qg + Qd + Qb)` structural: the source row picks up the
        ## negative of the other three because each branch subtracts
        ## there, so charge conservation is a property of the topology
        ## rather than something to check numerically.
        ##
        ## `i[node]` is the current flowing FROM the node INTO the
        ## device -- the convention a generated resistor uses, where
        ## `I(p,m) <+ V/r` makes `i[p]` positive for `vp > vm`.  So for
        ## an n-channel with the drain above the source the drain entry
        ## is +Ids.
        ## Undo the ordering.  `Qg` and `Qb` are even under the exchange
        ## and pass through untouched; the channel charge splits between
        ## the two ends and has to follow the terminals.  With
        ## `Qch = -(Qg + Qb)` the forward result gives the HIGH end `Qd`
        ## and the low end `Qch - Qd`, so interpolating on `sgn`
        ## reproduces each exactly at either polarity and averages them
        ## at `Vds = 0`, where the two ends are genuinely equal.
        qch = var(-(Qg + Qb), 'qch')
        qd_t = var(0.5 * qch + 0.5 * sgn * (2.0 * Qd - qch), 'qd_t')

        ## Polarity restored, exactly as PSP restores it
        ## (`PSP103_module.include:1701, 1788-1790`).  `sgn` is NOT
        ## multiplied by `T`: it is the internal source/drain interchange
        ## sign, a separate mechanism that already lives inside the
        ## internal convention.
        ## OVERLAP AND FRINGE CHARGE.
        ##
        ## `VgsPrime` and `VgdPrime` are, in PSP's own words, the
        ## "voltages NOT subject to S/D-interchange"
        ## (`PSP103_module.include:1051-1055`) -- the ACTUAL terminal
        ## voltages, not the ordered ones the channel uses.  That is
        ## right and not an oversight: the overlap sits over a physical
        ## diffusion, and which diffusion is momentarily the source does
        ## not move it.  The pair stays even under the exchange because
        ## the drain-side parameters mirror the source-side ones
        ## (`SWJUNASYM = 0`), so the two charges simply swap.
        vgsp = var(vgb - vsb, 'vgsp')
        vgdp = var(vgb - vdb, 'vgdp')

        def _vov(vgp, tag):
            ## The overlap region's surface potential, in closed form
            ## (`module:1182-1189`).  `spx` is a smoothed `max(xg_ov, 0)`
            ## -- and because `ov_eps2` is ~2700 on this card the
            ## radicands below never come near zero, so no guarding is
            ## needed on either square root.
            xgo = var(-vgp / phit0, 'xgov' + tag)
            spx = var(0.5 * (xgo + sympy.sqrt(xgo * xgo + ov_eps2)),  # noqa
                      'spx' + tag)
            xov = var(-spx - gov2 * 0.5                            # noqa
                      + gov * sympy.sqrt(spx + gov2 * 0.25 + ov_a)  # noqa
                      + ov_d1, 'xov' + tag)                        # noqa
            return var(-phit0 * (xgo + xov), 'vov' + tag)

        ## PSP folds the overlap into the fringe charge and contributes
        ## the sum (`module:1774-1775, 1791-1792`).
        q_gs = var(cfr * vgsp + cgov * _vov(vgsp, 's'), 'q_gs')  # noqa
        q_gd = var(cfr * vgdp + cgov * _vov(vgdp, 'd'), 'q_gd')  # noqa
        q_gb = var(cgbov * vgb, 'q_gb')                          # noqa

        ## THE JUNCTIONS.  `Vjun = -Vsb` in the internal convention, for
        ## BOTH channel types: PSP writes `Vjun_s = -V(SI,BS)` for
        ## n-channel and `+V(SI,BS)` for p-channel
        ## (`PSP103_module.include:1035-1048`), which is the same thing
        ## once the terminal voltages carry `T`.  Anode is the bulk, so
        ## a negative `Vjun` is reverse bias.
        ##
        ## Not ordered: a junction sits on a physical diffusion, like
        ## the overlap capacitance and for the same reason.
        ## The parameter symbols are injected into this function's
        ## globals by the DSL, so they are collected by NAME rather than
        ## written out -- seventy of them.
        _g_ = globals()
        jpar = {n: _g_[n] for n, _ in _JUNCAP_SHARED}
        for _c in ('bot', 'sti', 'gat'):
            for _k, _ in _JUNCAP_PER_COMPONENT:
                jpar['j%s_%s' % (_c, _k)] = _g_['j%s_%s' % (_c, _k)]

        vjs = var(-vsb, 'vjun_s')
        vjd = var(-vdb, 'vjun_d')
        qj_s, qj_d = (juncap.charge(vjs, jpar, 's'),
                      juncap.charge(vjd, jpar, 'd'))
        ij_s = juncap.current(vjs, jpar, 's') + juncap.leakage(vjs, jpar, 's')
        ij_d = juncap.current(vjd, jpar, 'd') + juncap.leakage(vjd, jpar, 'd')

        ## CHANNEL NOISE, on the same branch the current is on
        ## (`PSP103_module.include:1948-1949`).  Both densities come out
        ## of the surface-potential quantities the current already used,
        ## which is what a surface-potential model buys: there is no
        ## separate noise model to fit.
        n_sid, n_sfl, n_shared = psp_kernel.noise(
            core, None, beta, phit0, cox,
            dict(fnt=fnt, nfa=nfa, nfb=nfb, nfc=nfc))   # noqa: F821

        ## INDUCED GATE NOISE, as PSP builds it: an auxiliary node
        ## carrying a conductance, a capacitance and the shared source,
        ## with the gate reading the capacitor's current
        ## (`PSP103_module.include:1942-1948`).  The node is what makes
        ## the frequency shape come out of the CIRCUIT -- the density
        ## rises as `f^2` and rolls off above `1/(2 pi mig CGeff)`
        ## because an RC does that, not because anyone wrote it down.
        ign = psp_kernel.induced_gate_noise(core, n_shared, n_sid,
                                            cox_c, swign)  # noqa: F821
        noi = Node('noi')
        br_noi = Branch(noi, s, 'noi')
        ## `sqrt(mult)` on the coupled paths, not `mult`: these are
        ## AMPLITUDES sharing one source, so the power they carry into
        ## `CY` picks up `mult` when the amplitudes are squared there.
        ## Writing `mult` here would give `mult^2` in the density.
        sqm = var(sympy.sqrt(sympy.Max(mult, 0.0)), 'sqmult')  # noqa: F821

        ## MULTIPLICITY.  PSP multiplies every contribution by `MULT_i`
        ## (`MULT * NF`, `PSP103_scaling.include:828`); `m` devices in
        ## parallel carry `mult` times the current and charge, and
        ## present `rg/mult` of gate resistance -- so the resistor's
        ## CONDUCTANCE scales the same way everything else does.
        return (Contribution(br_rg.I,
                             mult * br_rg.V / rg),  # noqa: F821
                Collapse(br_rg, rg <= 0),                      # noqa: F821
                Contribution(Branch(d, s, 'chan').I,
                             mult * T * sgn * core['ids']),    # noqa: F821
                Contribution(Branch(gi, s, 'qg').I,
                             ddt(mult * T * Qg)),              # noqa: F821
                Contribution(Branch(b, s, 'qb').I,
                             ddt(mult * T * Qb)),              # noqa: F821
                Contribution(Branch(d, s, 'qd').I,
                             ddt(mult * T * qd_t)),            # noqa: F821
                ## Each of these is a gate-referenced PAIR, so charge
                ## conservation stays structural: every one adds at the
                ## gate and subtracts at exactly one other terminal.
                Contribution(Branch(gi, s, 'qovs').I,
                             ddt(mult * T * q_gs)),            # noqa: F821
                Contribution(Branch(gi, d, 'qovd').I,
                             ddt(mult * T * q_gd)),            # noqa: F821
                Contribution(Branch(gi, b, 'qovb').I,
                             ddt(mult * T * q_gb)),            # noqa: F821
                ## `I(BS,SI)` and `I(BD,DI)` (`module:1715-1716`,
                ## `:1794-1795`) -- bulk-referenced, so conservation
                ## stays structural here too.
                Contribution(Branch(b, s, 'jqs').I,
                             ddt(mult * T * qj_s)),            # noqa: F821
                Contribution(Branch(b, d, 'jqd').I,
                             ddt(mult * T * qj_d)),            # noqa: F821
                Contribution(Branch(b, s, 'jis').I,
                             mult * T * ij_s),                 # noqa: F821
                Contribution(Branch(b, d, 'jid').I,
                             mult * T * ij_d),                 # noqa: F821
                ## THE AUXILIARY NOISE NODE.  A conductance, a
                ## capacitance and the shared source -- the network
                ## whose impedance IS the frequency shape of the
                ## induced gate density.
                ##
                ## Collapsed away entirely when the term is INERT, which
                ## is `swign = 0` or `fnt = 0` -- the gate density is
                ## proportional to `nt`, so a device with no thermal
                ## noise has no induced gate noise either.  Both are
                ## non-negative parameters, so their product tests both
                ## at once.  Written this way an element built without a
                ## card is exactly the four-node element it was: the row
                ## is the price of the physics, not of the option.
                Contribution(br_noi.I, br_noi.V * ign['gcond']),
                Contribution(br_noi.I, ddt(ign['cgeff'] * br_noi.V)),
                Contribution(br_noi.I, white_noise(ign['pwr'], 'igid')),
                Collapse(br_noi, swign * fnt <= 0),            # noqa: F821
                ## The gate reads the capacitor's current, HALF to each
                ## channel end (`module:1945-1946`).  Split that way it
                ## stays a gate-referenced pair, so the coupling adds no
                ## net charge -- the same discipline the overlap
                ## contributions above keep.
                Contribution(Branch(gi, s, 'ign_s').I,
                             ddt(-sqm * 0.5 * ign['cgeff'] * br_noi.V)),
                Contribution(Branch(gi, d, 'ign_d').I,
                             ddt(-sqm * 0.5 * ign['cgeff'] * br_noi.V)),
                ## Noise densities are POWERS, so they carry `mult` but
                ## not `T` -- a spectral density has no sign.  The
                ## channel's own white term is reduced by `c_igid^2`,
                ## which the CORRELATED source below puts back: the two
                ## still sum to `Sid`, and the drain-drain entry of `CY`
                ## is therefore unchanged by any of this.  What changes
                ## is the gate, and the CROSS terms -- which is the
                ## whole point of the pair.
                Contribution(Branch(d, s, 'chan').I,
                             white_noise(mult * n_sid                 # noqa
                                         * (1.0 - ign['c2']))
                             + flicker_noise(mult * n_sfl, ef)),      # noqa
                ## `sigVds` and no `CHNL_TYPE` -- PSP's own signs
                ## (`module:1947`).  The relative sign between this and
                ## the gate coupling is the physics; the absolute one
                ## is not observable.
                Contribution(Branch(d, s, 'chan').I,
                             sgn * sqm * ign['migid']
                             * white_noise(ign['pwr'], 'igid')))


    return analog



#: JUNCAP2's per-component constants, and their defaults.  Kept beside
#: the generator rather than in it so the list reads as data.
_JUNCAP_PER_COMPONENT = (
    ('p', 0.5), ('vbi', 1.0), ('qpref', 0.0), ('qpref2', 0.0),
    ('area', 0.0), ('idsat', 0.0), ('csrh', 0.0), ('ctat', 0.0),
    ('cbbt', 0.0), ('vbir', 1.0), ('vbirinv', 1.0), ('wdepnulr', 1.0),
    ('wdepnulrinv', 1.0), ('omp', 0.5), ('oomp', 2.0), ('atat', 1.0),
    ('btatpart', 1.0), ('fbbt', 0.0), ('vbr', 10.0), ('pbr', 4.0),
    ('fstop', 1.0), ('vbrinv', 0.1), ('slope', 0.0), ('ftd', 1.0),
)

#: The shared ones.
_JUNCAP_SHARED = (
    ('jphit', 0.02585), ('jphitr', 0.02585), ('jvfmin', 0.5),
    ('jvch', 0.07), ('jvmax', 1.0), ('jisat', 0.0), ('jvbimin', 1.0),
    ('jvbbtlim', 0.5), ('jalphaav', 0.999), ('jperfc', 0.5178),
    ('jberfc', 0.2699), ('jcerfc', 0.4379),
)


def _juncap_params():
    """The junction's `Parameter` objects, generated."""
    out = [Parameter(name=n, desc='JUNCAP %s' % n, unit='', default=d)
           for n, d in _JUNCAP_SHARED]
    for c in ('bot', 'sti', 'gat'):
        out += [Parameter(name='j%s_%s' % (c, n),
                          desc='JUNCAP %s %s' % (c, n), unit='',
                          default=d)
                for n, d in _JUNCAP_PER_COMPONENT]
    return out


class PspMosLongChannel(Behavioural):
    """A surface-potential MOSFET: PSP103's core, from a real card.

    Not PSP103, but no longer only its centre.  The surface potential is
    solved at each channel end by `psp_kernel.sp_s` and the drain
    current assembled from them by symmetric linearisation; on top of
    that sit mobility reduction, Coulomb scattering, velocity
    saturation, series resistance, the saturation-limited drain voltage,
    channel-length modulation with its channel-shortening factor, the
    quantum-mechanical correction, polysilicon depletion and the
    effective thermal voltage.  Parameters come from a foundry card
    through `psp_scaling.to_long_channel`, with nothing fitted, and the
    drain current agrees with IHP's own compiled PSP103 to within a few
    tenths of a percent across six sweeps and two geometries.

    Still absent: gate and junction leakage, impact ionisation, overlap
    and fringe capacitances, the non-quasi-static block, self-heating,
    and every temperature coefficient.  Two further blocks -- DIBL and
    the bias modulations of the velocity-saturation parameter -- are
    implemented but switched off, for reasons recorded on
    `psp_scaling.to_long_channel`.

    Four properties come out of the construction rather than out of
    fitting, and are the reason this class of model displaced
    threshold-voltage models:

    * the drain current is **antisymmetric** under exchanging source and
      drain, to a unit in the last place -- because the inversion charge
      is evaluated at the midpoint potential, and because the terminals
      are ordered rather than the formula being relied on to be odd;
    * it is **exactly zero** at zero drain-source bias, for any gate
      bias;
    * one expression covers accumulation, depletion, weak and strong
      inversion, with no regional equations and no smoothing functions
      pasted between them;
    * the four terminal charges sum to zero **structurally**, because
      three of them are contributed on branches referred to the source
      and the fourth is what is left.

    See `PspPmosLongChannel` for the p-channel device, which is this one
    with five terms changed.
    """

    instparams = [
        Parameter(name='w', desc='Channel width', unit='m', default=1e-6),
        Parameter(name='l', desc='Channel length', unit='m', default=1e-6),
        Parameter(name='tox', desc='Oxide thickness', unit='m',
                  default=2.2e-9),
        Parameter(name='nsub', desc='Substrate doping', unit='m^-3',
                  default=5e23),
        Parameter(name='vfb', desc='Flat-band voltage', unit='V',
                  default=-0.95),
        Parameter(name='u0', desc='Low-field mobility', unit='m^2/Vs',
                  default=0.045),
        Parameter(name='phib', desc='Surface potential at threshold '
                  '(2*phi_F)', unit='V', default=0.9),
        ## Mobility reduction and velocity saturation.  Defaults are the
        ## IHP SG13G2 n-channel card's, so the device behaves like a real
        ## 130 nm transistor rather than an ideal one; setting `mue`,
        ## `cs` and `thesat` to zero recovers the ideal long-channel
        ## core, which is what the construction tests exercise.
        Parameter(name='mue', desc='Mobility reduction coefficient',
                  unit='m/V', default=0.77874),
        Parameter(name='themu', desc='Mobility reduction exponent',
                  unit='', default=2.0546),
        Parameter(name='cs', desc='Coulomb scattering parameter', unit='',
                  default=0.3164),
        Parameter(name='thecs', desc='Coulomb scattering exponent',
                  unit='', default=1.1822),
        Parameter(name='feta', desc='Effective field parameter', unit='',
                  default=1.0),
        Parameter(name='thesat', desc='Velocity saturation parameter',
                  unit='1/V', default=0.39843),
        ## Series resistance.  PSP folds this into the mobility rather
        ## than adding a network element, which keeps the device
        ## four-terminal and symmetric; `rs = 0` disables it.
        Parameter(name='rs', desc='Intrinsic series resistance', unit='ohm',
                  default=0.0),
        Parameter(name='rsg', desc='Gate-bias dependence of rs', unit='',
                  default=0.0),
        Parameter(name='rsb', desc='Body-bias dependence of rs', unit='',
                  default=0.0),
        ## Interface states.  PSP normalises the gate drive, the
        ## quasi-Fermi levels and the charges by an EFFECTIVE thermal
        ## voltage `phit*(1 + ct)`, not by `phit` itself.
        Parameter(name='ct', desc='Interface-states factor', unit='',
                  default=0.0),
        ## Channel-length modulation; `alp = 0` disables it.
        Parameter(name='alp', desc='Channel-length modulation factor',
                  unit='', default=0.0),
        Parameter(name='vp', desc='CLM logarithmic parameter', unit='V',
                  default=0.05),
        Parameter(name='alp1', desc='CLM correction, strong inversion',
                  unit='', default=0.0),
        Parameter(name='alp2', desc='CLM correction, weak inversion',
                  unit='', default=0.0),
        ## The CV effective dimensions.  PSP builds the oxide
        ## capacitance for the CHARGE model from these rather than from
        ## the drawn ones (`PSP103_scaling.include:38-39, 359`); they
        ## default to the drawn dimensions so an element built without a
        ## card behaves as before.
        Parameter(name='wcv', desc='Effective width for charges',
                  unit='m', default=0.0),
        Parameter(name='lcv', desc='Effective length for charges',
                  unit='m', default=0.0),
        Parameter(name='qq', desc='Quantum correction coefficient',
                  unit='', default=0.0),
        ## Overlap and fringe.  The `ov_*` trio are the closed-form
        ## overlap surface potential's constants, computed once per
        ## instance in the scaling layer -- they depend on the doping
        ## and the overlap oxide, not on bias.
        Parameter(name='cgov', desc='Gate-diffusion overlap capacitance',
                  unit='F', default=0.0),
        Parameter(name='cfr', desc='Outer fringe capacitance', unit='F',
                  default=0.0),
        Parameter(name='cgbov', desc='Gate-bulk overlap capacitance',
                  unit='F', default=0.0),
        Parameter(name='gov', desc='Overlap body factor', unit='',
                  default=1.0),
        Parameter(name='gov2', desc='Overlap body factor squared',
                  unit='', default=1.0),
        Parameter(name='ov_a', desc='Overlap SP fit coefficient',
                  unit='', default=1.0),
        Parameter(name='ov_d1', desc='Overlap SP offset', unit='',
                  default=0.0),
        Parameter(name='ov_eps2', desc='Overlap SP smoothing', unit='',
                  default=1.0),
        ## JUNCAP2's constants (`psp_scaling.junction`).  All are
        ## bias-independent, so they arrive as numbers and none of the
        ## temperature or geometry arithmetic reaches the compiled
        ## expression.  The areas default to zero, which switches the
        ## junction off entirely; the rest default to values that keep
        ## the unused expressions finite.
        ##
        ## Generated rather than written out: there are three components
        ## with twenty-odd constants each, and a hand-written list of
        ## seventy `Parameter(...)` lines is a place for a typo to hide
        ## rather than something anyone will read.
        ] + _juncap_params() + [
        ## Channel noise.  `fnt = 0` switches the thermal term off and
        ## `nfa = nfb = nfc = 0` the flicker one, which is the default:
        ## an element built without a card is noiseless.
        Parameter(name='fnt', desc='Thermal noise coefficient', unit='',
                  default=0.0),
        Parameter(name='nfa', desc='Flicker noise, first coefficient',
                  unit='', default=0.0),
        Parameter(name='nfb', desc='Flicker noise, second coefficient',
                  unit='', default=0.0),
        Parameter(name='nfc', desc='Flicker noise, third coefficient',
                  unit='', default=0.0),
        Parameter(name='ef', desc='Flicker noise exponent', unit='',
                  default=1.0),
        ## `SWIGN` (`PSP103_parlist.include:48`).  Defaulting it ON
        ## costs nothing when the thermal term is off -- the induced
        ## gate density is proportional to `fnt` through `nt` -- and
        ## makes a card that sets it, as this one does, behave without
        ## having to say so twice.
        Parameter(name='swign', desc='Induced gate noise: 0=off, 1=on',
                  unit='', default=1.0),
        ## `EPSROXO` (`PSP103_parlist.include:257`).  A parameter and
        ## not a constant, because the card carries it.
        Parameter(name='epsrox', desc='Gate dielectric permittivity',
                  unit='', default=3.9),
        Parameter(name='rg', desc='Gate resistance', unit='ohm',
                  default=0.0),
        Parameter(name='mult', desc='Multiplicity (devices in parallel)',
                  unit='', default=1.0),
        Parameter(name='xcor', desc='Body-bias mobility correction',
                  unit='1/V', default=0.0),
        Parameter(name='dnsub', desc='Bias-dependent body factor',
                  unit='1/V', default=0.0),
        Parameter(name='vnsub', desc='Onset of the bias-dependent body '
                  'factor', unit='V', default=0.0),
        Parameter(name='nslp', desc='Smoothing of that onset', unit='V',
                  default=0.05),
        Parameter(name='cf', desc='DIBL coefficient', unit='',
                  default=0.0),
        Parameter(name='cfb', desc='DIBL body-bias dependence', unit='',
                  default=0.0),
        Parameter(name='cfd', desc='DIBL drain-bias saturation', unit='1/V',
                  default=0.0),
        Parameter(name='thesatb', desc='Body-bias modulation of thesat',
                  unit='1/V', default=0.0),
        Parameter(name='thesatg', desc='Gate-bias modulation of thesat',
                  unit='1/V', default=0.0),
        ## Linear/saturation transition sharpness.  PSP floors this at 2
        ## in its scaling, and the kernel floors it again -- a small `ax`
        ## makes the drain-voltage limiter soft enough to bite far below
        ## saturation.
        Parameter(name='ax', desc='Linear/saturation transition factor',
                  unit='', default=2.0),
        ## Polysilicon depletion; `kp = 0` is an ideal (metal) gate.
        Parameter(name='kp', desc='Polysilicon depletion factor', unit='',
                  default=0.0),
    ]

    #: Largest per-iteration excursion, in volts, allowed on any of the
    #: device's branch voltages.  1 V is loose enough to be inactive
    #: near a solution and tight enough that a Newton step cannot leave
    #: the region where the device has any gradient at all.
    vlimit = 1.0

    def bias(self, vd, vg, vs=0.0, vb=0.0):
        """The node-voltage vector for a given TERMINAL bias.

        Use this rather than building the vector by hand.  The element
        grows internal nodes as parasitics are switched on -- the gate
        resistance puts one behind `g` right now, and the junction model
        will add more -- so a hard-coded four-vector silently becomes
        the wrong length, and before that it silently addresses the
        wrong node.

        Internal nodes are set to their zero-current values, which is
        exact for a DC evaluation: no current flows into the gate, so
        the internal gate sits at the external one.
        """
        x = np.zeros(self.n, dtype=float)
        x[0], x[1], x[2], x[3] = vd, vg, vs, vb
        for k, node in enumerate(self.nodes):
            if str(node) == 'gi':
                x[k] = vg
        return x

    @property
    def gate_index(self):
        """Row and column of the INTRINSIC gate in this element's
        matrices.

        With a gate resistance the intrinsic gate is an internal node,
        not the terminal: every charge the model contributes hangs off
        it, so the terminal's own row is empty and `C[1, 1]` is zero.
        PSP measures its `cgg` at the same place -- its internal `GP` --
        so this is the index a comparison against it wants.
        """
        for k, node in enumerate(self.nodes):
            if str(node) == 'gi':
                return k
        return 1

    def limit(self, x, x0, epar=defaultepar):
        """Bound this device's branch voltages per Newton iteration.

        THIS IS NOT OPTIONAL FOR A SATURATING MODEL, which is a thing
        the core only became when the drain voltage started being
        limited to `Vdsat`.  Before that the current kept growing with
        `Vds` and a Newton step that overshot still had a gradient
        pointing home.  Now the current saturates -- correctly; that is
        what `Vdse` is for -- and `dIds/dVds` falls to 1e-11 by 500 V and
        1e-28 by 1e7.  A solver that lands out there is not slow, it is
        stuck: the row goes numerically empty and the matrix is reported
        singular.  A stacked pair driving its own internal node was
        enough to walk out there and stay.

        So this plays the part SPICE gives `DEVfetlim`, in the state-free
        form the tree prefers (`SubCircuit.limit`): return a limited copy
        of the sub-vector, so the residual and the Jacobian are always
        taken at the same point.  The source is left where the solver put
        it -- it is some other device's drain, and limiting it here would
        have the two fight -- and the other three terminals are bounded
        relative to it, which is what SPICE bounds too.
        """
        out = np.array(x, dtype=float, copy=True)
        x0a = np.asarray(x0, dtype=float)
        vs, vs0 = out[2], x0a[2]
        lim = self.vlimit
        for k in (0, 1, 3):
            vold = x0a[k] - vs0
            delta = (out[k] - vs) - vold
            if abs(delta) > lim:
                out[k] = vs + vold + (lim if delta > 0.0 else -lim)
        return out

    analog = staticmethod(_psp_mos_analog(1.0, False))


class PspPmosLongChannel(PspMosLongChannel):
    """The p-channel device: the same core, run in PSP's own way.

    Terminals, parameters and the Newton limiter are inherited
    unchanged.  The model card supplies the difference and nothing here
    does: every parameter on IHP's p-channel card is a positive
    magnitude carrying the same signs as the n-channel one -- `vfbo` is
    negative on both -- and the polarity lives in a single `type = -1`
    on the `.model` line.  PSP's 849-line geometry-scaling layer
    contains not one reference to the channel type, for the same reason.

    Redefining `analog` is REQUIRED rather than decorative: the DSL keys
    compilation on the name appearing in the class body, so a subclass
    that merely inherited it would silently reuse the n-channel
    expression and be wrong in a way nothing would report.
    """

    analog = staticmethod(_psp_mos_analog(-1.0, True))
