"""Production compact models written in the Behavioural DSL.

`elements_hdl.py` re-expresses the classical elements to prove the DSL
equals `elements.py`.  This module is the other direction: real foundry
compact models, translated from their shipped Verilog-A and checked
against the vendor's own compiled binary.

The reference data lives in `tests/data/` and is generated by the
scripts in `benchmarks/` from the IHP Open PDK (SG13G2), which ships
Verilog-A sources, compiled OSDI binaries and extracted model cards.

Currently: `CapCmomi`.
"""

import sympy

from pycircuit.circuit.hdl import (Behavioural, Branch, Contribution, Node,
                                   ddt)
from pycircuit.utilities.param import Parameter


#: Weak anchor conductance so a floating port or internal island never
#: gives a singular matrix.  The vendor's ``GLEAK``.  Module level, not a
#: class attribute: `analog()` runs while the class body is still being
#: executed, so the class name does not exist yet.
GLEAK = 1.0e-12


def _sel(pairs, default):
    """A parameter-keyed selection, as Verilog-A's nested ``? :``.

    ``pairs`` is ``[(condition, value), ...]`` tried in order.  Written
    as one `Piecewise` rather than nested ones so the compiled `select`
    is flat, and so the fall-through is visible in one place.
    """
    return sympy.Piecewise(*([(v, c) for c, v in pairs] + [(default, True)]))


class CapCmomi(Behavioural):
    """Interdigitated metal-oxide-metal capacitor -- IHP ``cap_cmomi``.

    Translated from ``ihp-sg13g2/libs.tech/verilog-a/cap_cmomi/cap_cmomi.va``
    (314 lines).  An EM-fitted RF equivalent circuit:

    .. code-block:: text

        PLUS --(Lskin || Rskin)-- Cmain --(Lcore)--(Rseries)-- MINUS
                                              |
                                             Cox      (shunt off the MINUS side)
                                              |
                                        (Rsub || Csub)
                                              |
                                             SUB

    Every coefficient is selected by the metal LAYER COUNT
    ``N = mmax - mmin + 1`` (and, for the oxide shunt, by the bottom-metal
    index), and the core inductance is keyed by feed style: ``feed=double``
    takes the two-sided loop fit, ``same``/``none`` recover the much
    smaller single-side inductance from the model's own capacitance and a
    fitted self-resonance.  The comments below record only what the
    translation had to decide; the physics provenance is in the vendor
    header.

    ``$mfactor`` is deliberately not applied.  The vendor model reads it
    but does NOT scale its elements by it -- the simulator multiplies the
    device stamps by ``m`` itself, and scaling here too would give ``m**2``.
    The vendor source says so in a comment; see hdl.md Phase E.

    Verified against the PDK's own OSDI build over 1 MHz - 100 GHz for ten
    configurations covering every coefficient branch
    (`test_compact_cap_cmomi.py`, reference generated by
    `benchmarks/cap_cmomi_reference.py`).
    """

    instparams = [
        Parameter(name='w', desc='Width (Y, row stacking)', unit='m',
                  default=5e-6),
        Parameter(name='l', desc='Length (X, finger length)', unit='m',
                  default=5e-6),
        Parameter(name='mmin', desc='Bottom metal index', unit='',
                  default=1),
        Parameter(name='mmax', desc='Top metal index', unit='', default=5),
        Parameter(name='feed', desc='Feed code: 0=none 1=same 2=double',
                  unit='', default=2),
        Parameter(name='subblock', desc='Substrate-isolation block '
                  '(layout/LVS only, no electrical effect)', unit='',
                  default=0),
    ]

    @staticmethod
    def analog(PLUS, MINUS, SUB):
        nsk, ncap, nl, nox = (Node('nsk'), Node('ncap'), Node('nl'),
                              Node('nox'))

        ## Eight NAMED branches, three pairs of which share a node pair:
        ## the skin arm is an inductor in parallel with a resistor, and
        ## the substrate termination is a resistor in parallel with a
        ## capacitor.  Anonymous branches would merge each pair into one
        ## unknown and lose a constitutive relation.
        br_lskin = Branch(PLUS, nsk, 'lskin')
        br_rskin = Branch(PLUS, nsk, 'rskin')
        br_cmain = Branch(nsk, ncap, 'cmain')
        br_lcore = Branch(ncap, nl, 'lcore')
        br_rser = Branch(nl, MINUS, 'rser')
        br_cox = Branch(nl, nox, 'cox')
        br_rsub = Branch(nox, SUB, 'rsub')
        br_csub = Branch(nox, SUB, 'csub')
        br_lkp = Branch(PLUS, SUB, 'lkp')
        br_lkm = Branch(MINUS, SUB, 'lkm')

        ## Parameters arrive in SI; the fits are all in micrometres.
        lu = l * 1e6                                          # noqa: F821
        wu = w * 1e6                                          # noqa: F821
        lw = wu + lu
        ratio = lu / wu

        Nlay = sympy.Max(mmax - mmin + 1, 1)                  # noqa: F821

        ## Unit-cell tiling, 0.84 x 0.89 um, one y-row spent on the feed.
        ## The epsilon before the floor is the vendor's, and it is load-
        ## bearing: a drawn dimension that is an exact multiple of the
        ## pitch round-trips through *1e6 to one ulp below the integer,
        ## and floor() would then land on k or k-1 depending on whether
        ## the backend divides or multiplies by the reciprocal.  The
        ## model must agree with the PCell layout for every geometry, so
        ## the nudge (1e-6 cell = 0.84 pm, far below any layout grid)
        ## makes an exact k-pitch resolve to k everywhere.
        ax = sympy.floor(lu / 0.84 + 1e-6)
        ay = sympy.floor(wu / 0.89 + 1e-6) - 1
        active_x = sympy.Max(ax, 1)
        active_y = sympy.Max(ay, 1)
        active_area = active_x * active_y * 0.84 * 0.89
        feed_width = active_y * 0.89 + 0.64

        issame = _sel([(sympy.Eq(feed, 1), 1.0)], 0.0)         # noqa: F821

        ## Area density [fF/um^2] and single-side feed cap [fF/um] by N.
        density = _sel([(Nlay <= 2, 0.55),
                        (sympy.Eq(Nlay, 3), 0.82),
                        (sympy.Eq(Nlay, 4), 1.09)], 1.36)
        cfeed_pu = _sel([(Nlay <= 2, 0.70),
                         (sympy.Eq(Nlay, 3), 0.97),
                         (sympy.Eq(Nlay, 4), 1.28)], 1.46)

        cfeed_fF = issame * cfeed_pu * feed_width
        cmain_fF = density * active_area + cfeed_fF
        Cmain = cmain_fF * 1e-15

        ## Series resistance [ohm].  'same' is layer-independent; 'none'
        ## reuses the opposite-side set, which is the vendor's choice.
        Rseries = _sel(
            [(issame > 0.5, 0.22 + 0.40 * ratio),
             (Nlay <= 3, 0.10 + 0.31 * ratio),
             (sympy.Eq(Nlay, 4), 0.14 + 0.27 * ratio)],
            0.15 + 0.26 * ratio)
        Rseries = sympy.Max(Rseries, 1e-3)

        ## Core inductance, keyed by FEED.  feed=double is a real loop
        ## (current down one comb and back the other) worth tens of pH;
        ## same/none have no such loop, and their much smaller local
        ## inductance is recovered from this model's own Cmain and the
        ## fitted single-side self-resonance.
        srf_ss = _sel([(Nlay <= 3, 1e9 / (7.68e-5 + 6.64e-5 * lu)),
                       (sympy.Eq(Nlay, 4), 1e9 / (8.82e-4 + 4.72e-5 * lu))],
                      1e9 / (2.85e-4 + 6.87e-5 * lu))
        wsrf = 2 * sympy.pi * srf_ss
        Lcore = _sel(
            [(sympy.Eq(feed, 2),                              # noqa: F821
              (4.886 + 3.117 * ratio + 0.510 * lu
               - 2.526 * sympy.sqrt(lu)) * 1e-12)],
            1.0 / (wsrf * wsrf * Cmain))
        Lcore = sympy.Max(Lcore, 1e-18)

        ## Skin effect.
        Rskin1 = _sel([(Nlay <= 3, 0.031)], 0.035)
        Lskin_c = _sel([(Nlay <= 3, 0.214)], 0.010)
        Lskin_s = _sel([(Nlay <= 3, 0.02256)], 0.0626)
        Rskin = sympy.Max(Rskin1 * lu, 1e-3)
        Lskin = (Lskin_c + Lskin_s * lu) * 1e-12

        ## Oxide capacitance, keyed by the BOTTOM metal index -- the
        ## vendor's re-keying of coefficient sets the source notes index
        ## by layer count.
        cox0 = _sel([(sympy.Eq(mmin, 1), 1.725),              # noqa: F821
                     (sympy.Eq(mmin, 2), 1.240)], 1.052)      # noqa: F821
        cox1 = _sel([(sympy.Eq(mmin, 1), 0.1192),             # noqa: F821
                     (sympy.Eq(mmin, 2), 0.1139)], 0.09867)   # noqa: F821
        cox2 = _sel([(sympy.Eq(mmin, 1), 0.019406),           # noqa: F821
                     (sympy.Eq(mmin, 2), 0.011417)], 0.011364)  # noqa
        Cox = (cox0 + cox1 * lw + cox2 * wu * lu) * 1e-15

        Rsub = sympy.Max(3144.0 - 9.6942 * lw + 0.0207848 * wu * lu, 1e-2)
        Csub = (9.8833 + 0.089195 * lw + 0.000675931 * wu * lu) * 1e-15

        return (
            ## Skin arm: inductor (voltage-defined) || resistor.
            Contribution(br_lskin.V, ddt(Lskin * br_lskin.I)),
            Contribution(br_rskin.I, br_rskin.V / Rskin),
            ## Main capacitance, core inductance, series resistance.
            Contribution(br_cmain.I, ddt(Cmain * br_cmain.V)),
            Contribution(br_lcore.V, ddt(Lcore * br_lcore.I)),
            Contribution(br_rser.I, br_rser.V / Rseries),
            ## Substrate shunt: Cox in series with Rsub || Csub.
            Contribution(br_cox.I, ddt(Cox * br_cox.V)),
            Contribution(br_rsub.I, br_rsub.V / Rsub),
            Contribution(br_csub.I, ddt(Csub * br_csub.V)),
            ## Weak DC anchors, so a floating port or island never leaves
            ## the matrix singular.
            Contribution(br_lkp.I, GLEAK * br_lkp.V),
            Contribution(br_lkm.I, GLEAK * br_lkm.V),
        )
