"""Production compact models written in the Behavioural DSL.

`elements_hdl.py` re-expresses the classical elements to prove the DSL
equals `elements.py`.  This module is the other direction: real foundry
compact models, translated from their shipped Verilog-A and checked
against the vendor's own compiled binary.

The reference data lives in `tests/data/` and is generated by the
scripts in `benchmarks/` from the IHP Open PDK (SG13G2), which ships
Verilog-A sources, compiled OSDI binaries and extracted model cards.

Currently: `CapCmomi`.
"""

import sympy

from pycircuit.circuit import psp_kernel
from pycircuit.circuit.constants import (eps0, epsRSi, epsRSiO2,
                                         qelectron as QELEC)
from pycircuit.circuit.hdl import (Behavioural, Branch, Contribution, Node,
                                   ddt, var, vt)
from pycircuit.utilities.param import Parameter


#: Permittivities, from the toolkit's own constants so a generated stamp
#: matches a hand-written one exactly rather than nearly.
EPS_OX = epsRSiO2 * eps0
EPS_SI = epsRSi * eps0

#: 1/sqrt(2), as PSP spells it.
INV_SQRT2 = 7.0710678118654746e-01


#: Weak anchor conductance so a floating port or internal island never
#: gives a singular matrix.  The vendor's ``GLEAK``.  Module level, not a
#: class attribute: `analog()` runs while the class body is still being
#: executed, so the class name does not exist yet.
GLEAK = 1.0e-12


def _sel(pairs, default):
    """A parameter-keyed selection, as Verilog-A's nested ``? :``.

    ``pairs`` is ``[(condition, value), ...]`` tried in order.  Written
    as one `Piecewise` rather than nested ones so the compiled `select`
    is flat, and so the fall-through is visible in one place.
    """
    return sympy.Piecewise(*([(v, c) for c, v in pairs] + [(default, True)]))


class CapCmomi(Behavioural):
    """Interdigitated metal-oxide-metal capacitor -- IHP ``cap_cmomi``.

    Translated from ``ihp-sg13g2/libs.tech/verilog-a/cap_cmomi/cap_cmomi.va``
    (314 lines).  An EM-fitted RF equivalent circuit:

    .. code-block:: text

        PLUS --(Lskin || Rskin)-- Cmain --(Lcore)--(Rseries)-- MINUS
                                              |
                                             Cox      (shunt off the MINUS side)
                                              |
                                        (Rsub || Csub)
                                              |
                                             SUB

    Every coefficient is selected by the metal LAYER COUNT
    ``N = mmax - mmin + 1`` (and, for the oxide shunt, by the bottom-metal
    index), and the core inductance is keyed by feed style: ``feed=double``
    takes the two-sided loop fit, ``same``/``none`` recover the much
    smaller single-side inductance from the model's own capacitance and a
    fitted self-resonance.  The comments below record only what the
    translation had to decide; the physics provenance is in the vendor
    header.

    ``$mfactor`` is deliberately not applied.  The vendor model reads it
    but does NOT scale its elements by it -- the simulator multiplies the
    device stamps by ``m`` itself, and scaling here too would give ``m**2``.
    The vendor source says so in a comment; see hdl.md Phase E.

    Verified against the PDK's own OSDI build over 1 MHz - 100 GHz for ten
    configurations covering every coefficient branch
    (`test_compact_cap_cmomi.py`, reference generated by
    `benchmarks/cap_cmomi_reference.py`).
    """

    instparams = [
        Parameter(name='w', desc='Width (Y, row stacking)', unit='m',
                  default=5e-6),
        Parameter(name='l', desc='Length (X, finger length)', unit='m',
                  default=5e-6),
        Parameter(name='mmin', desc='Bottom metal index', unit='',
                  default=1),
        Parameter(name='mmax', desc='Top metal index', unit='', default=5),
        Parameter(name='feed', desc='Feed code: 0=none 1=same 2=double',
                  unit='', default=2),
        Parameter(name='subblock', desc='Substrate-isolation block '
                  '(layout/LVS only, no electrical effect)', unit='',
                  default=0),
    ]

    @staticmethod
    def analog(PLUS, MINUS, SUB):
        nsk, ncap, nl, nox = (Node('nsk'), Node('ncap'), Node('nl'),
                              Node('nox'))

        ## Eight NAMED branches, three pairs of which share a node pair:
        ## the skin arm is an inductor in parallel with a resistor, and
        ## the substrate termination is a resistor in parallel with a
        ## capacitor.  Anonymous branches would merge each pair into one
        ## unknown and lose a constitutive relation.
        br_lskin = Branch(PLUS, nsk, 'lskin')
        br_rskin = Branch(PLUS, nsk, 'rskin')
        br_cmain = Branch(nsk, ncap, 'cmain')
        br_lcore = Branch(ncap, nl, 'lcore')
        br_rser = Branch(nl, MINUS, 'rser')
        br_cox = Branch(nl, nox, 'cox')
        br_rsub = Branch(nox, SUB, 'rsub')
        br_csub = Branch(nox, SUB, 'csub')
        br_lkp = Branch(PLUS, SUB, 'lkp')
        br_lkm = Branch(MINUS, SUB, 'lkm')

        ## Parameters arrive in SI; the fits are all in micrometres.
        lu = l * 1e6                                          # noqa: F821
        wu = w * 1e6                                          # noqa: F821
        lw = wu + lu
        ratio = lu / wu

        Nlay = sympy.Max(mmax - mmin + 1, 1)                  # noqa: F821

        ## Unit-cell tiling, 0.84 x 0.89 um, one y-row spent on the feed.
        ## The epsilon before the floor is the vendor's, and it is load-
        ## bearing: a drawn dimension that is an exact multiple of the
        ## pitch round-trips through *1e6 to one ulp below the integer,
        ## and floor() would then land on k or k-1 depending on whether
        ## the backend divides or multiplies by the reciprocal.  The
        ## model must agree with the PCell layout for every geometry, so
        ## the nudge (1e-6 cell = 0.84 pm, far below any layout grid)
        ## makes an exact k-pitch resolve to k everywhere.
        ax = sympy.floor(lu / 0.84 + 1e-6)
        ay = sympy.floor(wu / 0.89 + 1e-6) - 1
        active_x = sympy.Max(ax, 1)
        active_y = sympy.Max(ay, 1)
        active_area = active_x * active_y * 0.84 * 0.89
        feed_width = active_y * 0.89 + 0.64

        issame = _sel([(sympy.Eq(feed, 1), 1.0)], 0.0)         # noqa: F821

        ## Area density [fF/um^2] and single-side feed cap [fF/um] by N.
        density = _sel([(Nlay <= 2, 0.55),
                        (sympy.Eq(Nlay, 3), 0.82),
                        (sympy.Eq(Nlay, 4), 1.09)], 1.36)
        cfeed_pu = _sel([(Nlay <= 2, 0.70),
                         (sympy.Eq(Nlay, 3), 0.97),
                         (sympy.Eq(Nlay, 4), 1.28)], 1.46)

        cfeed_fF = issame * cfeed_pu * feed_width
        cmain_fF = density * active_area + cfeed_fF
        Cmain = cmain_fF * 1e-15

        ## Series resistance [ohm].  'same' is layer-independent; 'none'
        ## reuses the opposite-side set, which is the vendor's choice.
        Rseries = _sel(
            [(issame > 0.5, 0.22 + 0.40 * ratio),
             (Nlay <= 3, 0.10 + 0.31 * ratio),
             (sympy.Eq(Nlay, 4), 0.14 + 0.27 * ratio)],
            0.15 + 0.26 * ratio)
        Rseries = sympy.Max(Rseries, 1e-3)

        ## Core inductance, keyed by FEED.  feed=double is a real loop
        ## (current down one comb and back the other) worth tens of pH;
        ## same/none have no such loop, and their much smaller local
        ## inductance is recovered from this model's own Cmain and the
        ## fitted single-side self-resonance.
        srf_ss = _sel([(Nlay <= 3, 1e9 / (7.68e-5 + 6.64e-5 * lu)),
                       (sympy.Eq(Nlay, 4), 1e9 / (8.82e-4 + 4.72e-5 * lu))],
                      1e9 / (2.85e-4 + 6.87e-5 * lu))
        wsrf = 2 * sympy.pi * srf_ss
        Lcore = _sel(
            [(sympy.Eq(feed, 2),                              # noqa: F821
              (4.886 + 3.117 * ratio + 0.510 * lu
               - 2.526 * sympy.sqrt(lu)) * 1e-12)],
            1.0 / (wsrf * wsrf * Cmain))
        Lcore = sympy.Max(Lcore, 1e-18)

        ## Skin effect.
        Rskin1 = _sel([(Nlay <= 3, 0.031)], 0.035)
        Lskin_c = _sel([(Nlay <= 3, 0.214)], 0.010)
        Lskin_s = _sel([(Nlay <= 3, 0.02256)], 0.0626)
        Rskin = sympy.Max(Rskin1 * lu, 1e-3)
        Lskin = (Lskin_c + Lskin_s * lu) * 1e-12

        ## Oxide capacitance, keyed by the BOTTOM metal index -- the
        ## vendor's re-keying of coefficient sets the source notes index
        ## by layer count.
        cox0 = _sel([(sympy.Eq(mmin, 1), 1.725),              # noqa: F821
                     (sympy.Eq(mmin, 2), 1.240)], 1.052)      # noqa: F821
        cox1 = _sel([(sympy.Eq(mmin, 1), 0.1192),             # noqa: F821
                     (sympy.Eq(mmin, 2), 0.1139)], 0.09867)   # noqa: F821
        cox2 = _sel([(sympy.Eq(mmin, 1), 0.019406),           # noqa: F821
                     (sympy.Eq(mmin, 2), 0.011417)], 0.011364)  # noqa
        Cox = (cox0 + cox1 * lw + cox2 * wu * lu) * 1e-15

        Rsub = sympy.Max(3144.0 - 9.6942 * lw + 0.0207848 * wu * lu, 1e-2)
        Csub = (9.8833 + 0.089195 * lw + 0.000675931 * wu * lu) * 1e-15

        return (
            ## Skin arm: inductor (voltage-defined) || resistor.
            Contribution(br_lskin.V, ddt(Lskin * br_lskin.I)),
            Contribution(br_rskin.I, br_rskin.V / Rskin),
            ## Main capacitance, core inductance, series resistance.
            Contribution(br_cmain.I, ddt(Cmain * br_cmain.V)),
            Contribution(br_lcore.V, ddt(Lcore * br_lcore.I)),
            Contribution(br_rser.I, br_rser.V / Rseries),
            ## Substrate shunt: Cox in series with Rsub || Csub.
            Contribution(br_cox.I, ddt(Cox * br_cox.V)),
            Contribution(br_rsub.I, br_rsub.V / Rsub),
            Contribution(br_csub.I, ddt(Csub * br_csub.V)),
            ## Weak DC anchors, so a floating port or island never leaves
            ## the matrix singular.
            Contribution(br_lkp.I, GLEAK * br_lkp.V),
            Contribution(br_lkm.I, GLEAK * br_lkm.V),
        )


class PspMosLongChannel(Behavioural):
    """A surface-potential MOSFET: PSP's intrinsic long-channel core.

    Not PSP103.  This is PSP's *centre* -- the surface potential solved
    at each channel end by `psp_kernel.sp_s`, and the drain current
    assembled from them by symmetric linearisation -- with every
    short-channel, mobility, series-resistance, overlap, leakage and
    geometry-scaling layer omitted.  PSP103 is that core plus 2371 lines
    of those layers.

    What it demonstrates is the part that was in doubt: that the DSL can
    carry a surface-potential formulation at all.  Three properties come
    out of the construction rather than out of fitting, and are the
    reason this class of model displaced threshold-voltage models:

    * the drain current is **exactly antisymmetric** under exchanging
      source and drain, bit for bit -- because the inversion charge is
      evaluated at the midpoint potential;
    * it is **exactly zero** at zero drain-source bias, for any gate
      bias;
    * one expression covers accumulation, depletion, weak and strong
      inversion, with no regional equations and no smoothing functions
      pasted between them;
    * the four terminal charges sum to zero **structurally**, because
      three of them are contributed on branches referred to the source
      and the fourth is what is left.

    Parameters are the physical ones the core actually needs.  A real
    PSP card's 359 parameters mostly configure the layers that are not
    here, so this does not read one; `pycircuit.utilities.spicecard`
    exists for when it can.
    """

    instparams = [
        Parameter(name='w', desc='Channel width', unit='m', default=1e-6),
        Parameter(name='l', desc='Channel length', unit='m', default=1e-6),
        Parameter(name='tox', desc='Oxide thickness', unit='m',
                  default=2.2e-9),
        Parameter(name='nsub', desc='Substrate doping', unit='m^-3',
                  default=5e23),
        Parameter(name='vfb', desc='Flat-band voltage', unit='V',
                  default=-0.95),
        Parameter(name='u0', desc='Low-field mobility', unit='m^2/Vs',
                  default=0.045),
        Parameter(name='phib', desc='Surface potential at threshold '
                  '(2*phi_F)', unit='V', default=0.9),
        ## Mobility reduction and velocity saturation.  Defaults are the
        ## IHP SG13G2 n-channel card's, so the device behaves like a real
        ## 130 nm transistor rather than an ideal one; setting `mue`,
        ## `cs` and `thesat` to zero recovers the ideal long-channel
        ## core, which is what the construction tests exercise.
        Parameter(name='mue', desc='Mobility reduction coefficient',
                  unit='m/V', default=0.77874),
        Parameter(name='themu', desc='Mobility reduction exponent',
                  unit='', default=2.0546),
        Parameter(name='cs', desc='Coulomb scattering parameter', unit='',
                  default=0.3164),
        Parameter(name='thecs', desc='Coulomb scattering exponent',
                  unit='', default=1.1822),
        Parameter(name='feta', desc='Effective field parameter', unit='',
                  default=1.0),
        Parameter(name='thesat', desc='Velocity saturation parameter',
                  unit='1/V', default=0.39843),
        ## Series resistance.  PSP folds this into the mobility rather
        ## than adding a network element, which keeps the device
        ## four-terminal and symmetric; `rs = 0` disables it.
        Parameter(name='rs', desc='Intrinsic series resistance', unit='ohm',
                  default=0.0),
        Parameter(name='rsg', desc='Gate-bias dependence of rs', unit='',
                  default=0.0),
        Parameter(name='rsb', desc='Body-bias dependence of rs', unit='',
                  default=0.0),
        ## Interface states.  PSP normalises the gate drive, the
        ## quasi-Fermi levels and the charges by an EFFECTIVE thermal
        ## voltage `phit*(1 + ct)`, not by `phit` itself.
        Parameter(name='ct', desc='Interface-states factor', unit='',
                  default=0.0),
        ## Channel-length modulation; `alp = 0` disables it.
        Parameter(name='alp', desc='Channel-length modulation factor',
                  unit='', default=0.0),
        Parameter(name='vp', desc='CLM logarithmic parameter', unit='V',
                  default=0.05),
    ]

    @staticmethod
    def analog(d, g, s, b):
        bd, bg, bs = Branch(d, b, 'd'), Branch(g, b, 'g'), Branch(s, b, 's')

        ## Two thermal voltages, deliberately.  The BODY FACTOR is built
        ## on the plain one -- PSP's `G_0` is, and it only moves to the
        ## effective one under `SWFIX`, which defaults off.  Everything
        ## else -- gate drive, quasi-Fermi levels, charges, the current --
        ## is in units of the effective one.
        phit0 = var(vt(), 'phit0')
        phit = var(phit0 * (1.0 + ct), 'phit')                # noqa: F821
        ## Oxide capacitance per unit area, and the body factor that
        ## follows from it.  `Gf` is gamma normalised by sqrt(phit),
        ## which is the form the surface-potential solver takes.
        cox = var(EPS_OX / tox, 'cox')                        # noqa: F821
        gamma = var(sympy.sqrt(2.0 * QELEC * EPS_SI * nsub)   # noqa: F821
                    / cox, 'gamma')
        Gf = var(gamma / sympy.sqrt(phit0), 'Gf')
        xi = var(1.0 + Gf * INV_SQRT2, 'xi')

        ## Normalised gate drive, and the quasi-Fermi levels at the two
        ## channel ends.  Everything is referred to the bulk, which is
        ## what keeps source and drain interchangeable.
        xg = var((bg.V - vfb) / phit, 'xg')                   # noqa: F821
        xn_s = var((phib + bs.V) / phit, 'xn_s')              # noqa: F821
        xn_d = var((phib + bd.V) / phit, 'xn_d')              # noqa: F821

        beta = var(u0 * cox * w / l, 'beta')                  # noqa: F821

        core = psp_kernel.intrinsic(
            xg, xn_s, xn_d, Gf, xi, phit, beta,
            mob=dict(mue=mue, themu=themu, cs=cs,          # noqa: F821
                     thecs=thecs, feta=feta, thesat=thesat,  # noqa: F821
                     rs=rs, rsg=rsg, rsb=rsb, vsb=bs.V,     # noqa: F821
                     alp=alp, vp=vp, vds=bd.V - bs.V,       # noqa: F821
                     cox_area=cox, eps_si=EPS_SI))
        cox_tot = var(cox * w * l, 'cox_tot')                 # noqa: F821
        Qg, Qd, Qb = psp_kernel.charges_long_channel(core, xg, phit,
                                                     cox_tot)

        ## The charges are contributed on branches referred to the
        ## SOURCE, exactly as PSP does it.  That makes
        ## `Qs = -(Qg + Qd + Qb)` structural: the source row picks up the
        ## negative of the other three because each branch subtracts
        ## there, so charge conservation is a property of the topology
        ## rather than something to check numerically.
        ##
        ## `i[node]` is the current flowing FROM the node INTO the
        ## device -- the convention a generated resistor uses, where
        ## `I(p,m) <+ V/r` makes `i[p]` positive for `vp > vm`.  So for
        ## an n-channel with the drain above the source the drain entry
        ## is +Ids.
        return (Contribution(Branch(d, s, 'chan').I, core['ids']),
                Contribution(Branch(g, s, 'qg').I, ddt(Qg)),
                Contribution(Branch(b, s, 'qb').I, ddt(Qb)),
                Contribution(Branch(d, s, 'qd').I, ddt(Qd)))
