"""The golden PSP103 reference, and whether it is worth believing.

`data/psp103_ihp_iv.json` holds I-V curves for the IHP SG13G2 open PDK's
PSP 103.8.2 MOSFETs, swept in ngspice through the PDK's own compiled OSDI
binary and its extracted 359-parameter model cards.  It is what
pycircuit's compact-model work gets to be *right against*.

A reference nobody checks is a liability: it is generated by a script
that talks to an external simulator, and the ways it can be quietly wrong
-- recording the swept source's current instead of the drain's, a flipped
sign convention, a corner that never got selected -- all produce a file
that loads fine and means nothing.  So these tests assert the *physics*,
not just the shape.  Every threshold below is a property of a working
130 nm n-channel MOSFET, not a number copied out of this particular file.

The tests never invoke ngspice.  Regenerate with
``python benchmarks/psp_reference.py``.
"""
import json
import os

import numpy as np
import pytest


DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                    'data', 'psp103_ihp_iv.json')

#: Room-temperature thermal limit on subthreshold swing, mV/decade.
#: kT/q * ln(10) at 300 K.  No MOSFET beats it.
SS_LIMIT_MV = 59.6


@pytest.fixture(scope='module')
def ref():
    with open(DATA) as fh:
        return json.load(fh)


def _curve(ref, name):
    s = ref['sweeps'][name]
    return np.asarray(s['v'], float), np.asarray(s['i_d'], float), s


class TestTheFileIsIntact(object):

    def test_loads_and_names_its_provenance(self, ref):
        assert 'PSP 103.8.2' in ref['source']
        assert 'ngspice' in ref['simulator']
        assert ref['corner'] == 'mos_tt'

    @pytest.mark.parametrize('name', [
        'nmos_idvd_vg1p2', 'nmos_idvd_vg0p6', 'nmos_idvg_vd0p05',
        'nmos_idvg_vd1p2', 'nmos_idvg_vb_m1', 'nmos_long_idvd',
        'pmos_idvd_vg1p2'])
    def test_every_sweep_is_complete(self, ref, name):
        v, i, s = _curve(ref, name)
        assert len(v) >= 31
        assert len(i) == len(v)
        assert len(s['i_g']) == len(v)
        assert len(s['i_b']) == len(v)
        assert np.all(np.isfinite(v)) and np.all(np.isfinite(i))
        ## a monotone sweep, so nothing was concatenated or reordered
        assert np.all(np.diff(v) > 0)
        for key in ('device', 'w', 'l', 'sweep', 'bias', 'note'):
            assert key in s


class TestItIsActuallyATransistor(object):
    """Properties of a 130 nm MOSFET that no mis-recorded file has."""

    def test_subthreshold_swing_is_physical(self, ref):
        """Above the thermal limit, and below what a broken device shows.

        This is the single most diagnostic number: if the file recorded
        gate leakage instead of drain current, or the wrong corner, this
        fails immediately.
        """
        v, i, _ = _curve(ref, 'nmos_idvg_vd0p05')
        i = np.abs(i)
        m = (i > 1e-11) & (i < 1e-7)
        assert m.sum() >= 8, 'no usable subthreshold decade'
        slope = np.polyfit(v[m], np.log10(i[m]), 1)[0]
        ss_mv = 1000.0 / slope
        assert SS_LIMIT_MV < ss_mv < 150.0, 'swing %.1f mV/dec' % ss_mv

    def test_on_current_is_the_right_order(self, ref):
        """~400 uA/um at Vg = Vd = 1.2 V is what a 130 nm node gives."""
        v, i, s = _curve(ref, 'nmos_idvd_vg1p2')
        per_um = abs(np.interp(1.2, v, i)) / (s['w'] * 1e6)
        assert 100e-6 < per_um < 1e-3, '%.3g A/um' % per_um

    def test_it_saturates(self, ref):
        """Beyond pinch-off the current flattens: no resistor does this."""
        v, i, _ = _curve(ref, 'nmos_idvd_vg1p2')
        i = np.abs(i)
        lin = np.interp(0.15, v, i) / 0.15          # slope near the origin
        sat = (np.interp(1.5, v, i) - np.interp(0.9, v, i)) / 0.6
        assert sat < 0.1 * lin, 'not saturating: %.3g vs %.3g' % (sat, lin)
        ## and it is still rising a little -- a perfectly flat curve would
        ## mean the output conductance was dropped
        assert np.interp(1.5, v, i) > np.interp(0.9, v, i)

    def test_gate_bias_controls_the_channel(self, ref):
        v_hi, i_hi, _ = _curve(ref, 'nmos_idvd_vg1p2')
        v_lo, i_lo, _ = _curve(ref, 'nmos_idvd_vg0p6')
        assert abs(np.interp(1.2, v_hi, i_hi)) > \
            5 * abs(np.interp(1.2, v_lo, i_lo))

    def test_reverse_body_bias_raises_the_threshold(self, ref):
        """Vb = -1 V must REDUCE the current at fixed Vg."""
        v0, i0, _ = _curve(ref, 'nmos_idvg_vd0p05')
        vb, ib, _ = _curve(ref, 'nmos_idvg_vb_m1')
        at0 = abs(np.interp(1.2, v0, i0))
        atb = abs(np.interp(1.2, vb, ib))
        assert atb < at0
        assert atb > 0.4 * at0, 'implausibly large body effect'

    def test_dibl_is_present_and_bounded(self, ref):
        """Raising Vd lowers the threshold -- a short-channel effect.

        Its absence would mean the geometry-scaling layer never ran; a
        huge value would mean the device is punching through.
        """
        v0, i0, _ = _curve(ref, 'nmos_idvg_vd0p05')
        v1, i1, _ = _curve(ref, 'nmos_idvg_vd1p2')
        i0, i1 = np.abs(i0), np.abs(i1)
        lvl = np.log10(1e-8)
        vg0 = np.interp(lvl, np.log10(i0[i0 > 0]), v0[i0 > 0])
        vg1 = np.interp(lvl, np.log10(i1[i1 > 0]), v1[i1 > 0])
        shift_mv = 1000.0 * (vg0 - vg1)
        assert 5.0 < shift_mv < 300.0, 'DIBL shift %.0f mV' % shift_mv

    def test_the_long_device_drives_less_per_micron(self, ref):
        """Geometry scaling is doing something, and in the right direction."""
        vs, isx, ss = _curve(ref, 'nmos_idvd_vg1p2')
        vl, il, sl = _curve(ref, 'nmos_long_idvd')
        short = abs(np.interp(1.2, vs, isx)) / (ss['w'] * 1e6)
        long_ = abs(np.interp(1.2, vl, il)) / (sl['w'] * 1e6)
        assert sl['l'] > 5 * ss['l']
        assert long_ < short

    def test_gate_current_is_leakage_not_drive(self, ref):
        """Guards the mistake this file was regenerated to fix.

        The first version recorded the swept source's current, so the
        transfer curves held gate leakage -- four orders of magnitude
        below the drain current, and entirely plausible-looking until
        plotted.
        """
        for name in ('nmos_idvg_vd0p05', 'nmos_idvg_vd1p2'):
            s = ref['sweeps'][name]
            i_d = np.max(np.abs(s['i_d']))
            i_g = np.max(np.abs(s['i_g']))
            assert i_d > 1e-5, '%s: drain current %.3g A' % (name, i_d)
            assert i_g < 1e-3 * i_d, '%s: gate current is not leakage' % name

    def test_pmos_conducts_with_the_opposite_polarity(self, ref):
        v, i, _ = _curve(ref, 'pmos_idvd_vg1p2')
        assert np.all(v <= 1e-12), 'p-channel sweep should be negative Vd'
        assert np.max(np.abs(i)) > 50e-6
        ## and it is weaker than the n-channel, as hole mobility requires
        vn, inn, _ = _curve(ref, 'nmos_idvd_vg1p2')
        assert np.max(np.abs(i)) < np.max(np.abs(inn))


class TestCurrentsBalance(object):

    def test_kirchhoff_holds_at_every_point(self, ref):
        """id + ig + ib + is = 0.

        `is` is not recorded, so this checks the weaker statement that
        the three recorded currents never exceed what the drain carries
        -- enough to catch a sign flip in one of them.
        """
        for name, s in ref['sweeps'].items():
            i_d = np.abs(np.asarray(s['i_d'], float))
            i_g = np.abs(np.asarray(s['i_g'], float))
            i_b = np.abs(np.asarray(s['i_b'], float))
            scale = max(np.max(i_d), 1e-12)
            assert np.max(i_g) <= scale, name
            assert np.max(i_b) <= scale, name

    def test_the_sign_convention_is_into_the_terminal(self, ref):
        """A positive Vd on an n-channel drives current INTO the drain."""
        v, i, _ = _curve(ref, 'nmos_idvd_vg1p2')
        assert np.interp(1.0, v, i) > 0
        ## and for the p-channel, out of it
        vp, ip, _ = _curve(ref, 'pmos_idvd_vg1p2')
        assert np.interp(-1.0, vp, ip) < 0
